// Code generated by elegen. DO NOT EDIT.
// Source: go.aporeto.io/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"time"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.aporeto.io/elemental"
)

// FirewallLicensingCreditsIdentity represents the Identity of the object.
var FirewallLicensingCreditsIdentity = elemental.Identity{
	Name:     "firewalllicensingcredits",
	Category: "firewalllicensingcredits",
	Package:  "licensingsrv",
	Private:  false,
}

// FirewallLicensingCreditsList represents a list of FirewallLicensingCredits
type FirewallLicensingCreditsList []*FirewallLicensingCredits

// Identity returns the identity of the objects in the list.
func (o FirewallLicensingCreditsList) Identity() elemental.Identity {

	return FirewallLicensingCreditsIdentity
}

// Copy returns a pointer to a copy the FirewallLicensingCreditsList.
func (o FirewallLicensingCreditsList) Copy() elemental.Identifiables {

	out := append(FirewallLicensingCreditsList{}, o...)
	return &out
}

// Append appends the objects to the a new copy of the FirewallLicensingCreditsList.
func (o FirewallLicensingCreditsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(FirewallLicensingCreditsList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*FirewallLicensingCredits))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o FirewallLicensingCreditsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o FirewallLicensingCreditsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the FirewallLicensingCreditsList converted to SparseFirewallLicensingCreditsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o FirewallLicensingCreditsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseFirewallLicensingCreditsList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToSparse(fields...).(*SparseFirewallLicensingCredits)
	}

	return out
}

// Version returns the version of the content.
func (o FirewallLicensingCreditsList) Version() int {

	return 1
}

// FirewallLicensingCredits represents the model of a firewalllicensingcredits
type FirewallLicensingCredits struct {
	// Represents enhanced support credits.
	EnhancedSupportCredits int `json:"EnhancedSupportCredits" msgpack:"EnhancedSupportCredits" bson:"enhancedsupportcredits" mapstructure:"EnhancedSupportCredits,omitempty"`

	// Represents firewall usage credits.
	FWUsageCredits int `json:"FWUsageCredits" msgpack:"FWUsageCredits" bson:"fwusagecredits" mapstructure:"FWUsageCredits,omitempty"`

	// Identifier of the object.
	ID string `json:"ID" msgpack:"ID" bson:"-" mapstructure:"ID,omitempty"`

	// Represents Prisma Cloud management credits.
	PrismaCloudCredits int `json:"PrismaCloudCredits" msgpack:"PrismaCloudCredits" bson:"prismacloudcredits" mapstructure:"PrismaCloudCredits,omitempty"`

	// Represents threat prevention usage credits.
	TPUsageCredits int `json:"TPUsageCredits" msgpack:"TPUsageCredits" bson:"tpusagecredits" mapstructure:"TPUsageCredits,omitempty"`

	// Represents traffic secured usage credits.
	TrafficSecuredCredits int `json:"TrafficSecuredCredits" msgpack:"TrafficSecuredCredits" bson:"trafficsecuredcredits" mapstructure:"TrafficSecuredCredits,omitempty"`

	// Represents URL filtering usage credits.
	URLFUsageCredits int `json:"URLFUsageCredits" msgpack:"URLFUsageCredits" bson:"urlfusagecredits" mapstructure:"URLFUsageCredits,omitempty"`

	// Stores additional information about an entity.
	Annotations map[string][]string `json:"annotations" msgpack:"annotations" bson:"annotations" mapstructure:"annotations,omitempty"`

	// List of tags attached to an entity.
	AssociatedTags []string `json:"associatedTags" msgpack:"associatedTags" bson:"associatedtags" mapstructure:"associatedTags,omitempty"`

	// Represents the user cloud account ID.
	CloudAccountID string `json:"cloudAccountID" msgpack:"cloudAccountID" bson:"cloudaccountid" mapstructure:"cloudAccountID,omitempty"`

	// internal idempotency key for a create operation.
	CreateIdempotencyKey string `json:"-" msgpack:"-" bson:"createidempotencykey" mapstructure:"-,omitempty"`

	// Creation date of the object.
	CreateTime time.Time `json:"createTime" msgpack:"createTime" bson:"createtime" mapstructure:"createTime,omitempty"`

	// Represents firewall resource.
	FirewallResource string `json:"firewallResource" msgpack:"firewallResource" bson:"firewallresource" mapstructure:"firewallResource,omitempty"`

	// Namespace tag attached to an entity.
	Namespace string `json:"namespace" msgpack:"namespace" bson:"namespace" mapstructure:"namespace,omitempty"`

	// Contains the list of normalized tags of the entities.
	NormalizedTags []string `json:"normalizedTags" msgpack:"normalizedTags" bson:"normalizedtags" mapstructure:"normalizedTags,omitempty"`

	// Defines if the object is protected.
	Protected bool `json:"protected" msgpack:"protected" bson:"protected" mapstructure:"protected,omitempty"`

	// Represents the cloud ngfw tenant ID.
	TenantID string `json:"tenantID" msgpack:"tenantID" bson:"tenantid" mapstructure:"tenantID,omitempty"`

	// The timestamp of this record.
	Timestamp time.Time `json:"timestamp" msgpack:"timestamp" bson:"timestamp" mapstructure:"timestamp,omitempty"`

	// internal idempotency key for a update operation.
	UpdateIdempotencyKey string `json:"-" msgpack:"-" bson:"updateidempotencykey" mapstructure:"-,omitempty"`

	// Last update date of the object.
	UpdateTime time.Time `json:"updateTime" msgpack:"updateTime" bson:"updatetime" mapstructure:"updateTime,omitempty"`

	// geographical hash of the data. This is used for sharding and
	// georedundancy.
	ZHash int `json:"-" msgpack:"-" bson:"zhash" mapstructure:"-,omitempty"`

	// Logical storage zone. Used for sharding.
	Zone int `json:"-" msgpack:"-" bson:"zone" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewFirewallLicensingCredits returns a new *FirewallLicensingCredits
func NewFirewallLicensingCredits() *FirewallLicensingCredits {

	return &FirewallLicensingCredits{
		ModelVersion:   1,
		Annotations:    map[string][]string{},
		AssociatedTags: []string{},
		NormalizedTags: []string{},
	}
}

// Identity returns the Identity of the object.
func (o *FirewallLicensingCredits) Identity() elemental.Identity {

	return FirewallLicensingCreditsIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *FirewallLicensingCredits) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *FirewallLicensingCredits) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *FirewallLicensingCredits) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesFirewallLicensingCredits{}

	s.EnhancedSupportCredits = o.EnhancedSupportCredits
	s.FWUsageCredits = o.FWUsageCredits
	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.PrismaCloudCredits = o.PrismaCloudCredits
	s.TPUsageCredits = o.TPUsageCredits
	s.TrafficSecuredCredits = o.TrafficSecuredCredits
	s.URLFUsageCredits = o.URLFUsageCredits
	s.Annotations = o.Annotations
	s.AssociatedTags = o.AssociatedTags
	s.CloudAccountID = o.CloudAccountID
	s.CreateIdempotencyKey = o.CreateIdempotencyKey
	s.CreateTime = o.CreateTime
	s.FirewallResource = o.FirewallResource
	s.Namespace = o.Namespace
	s.NormalizedTags = o.NormalizedTags
	s.Protected = o.Protected
	s.TenantID = o.TenantID
	s.Timestamp = o.Timestamp
	s.UpdateIdempotencyKey = o.UpdateIdempotencyKey
	s.UpdateTime = o.UpdateTime
	s.ZHash = o.ZHash
	s.Zone = o.Zone

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *FirewallLicensingCredits) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesFirewallLicensingCredits{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.EnhancedSupportCredits = s.EnhancedSupportCredits
	o.FWUsageCredits = s.FWUsageCredits
	o.ID = s.ID.Hex()
	o.PrismaCloudCredits = s.PrismaCloudCredits
	o.TPUsageCredits = s.TPUsageCredits
	o.TrafficSecuredCredits = s.TrafficSecuredCredits
	o.URLFUsageCredits = s.URLFUsageCredits
	o.Annotations = s.Annotations
	o.AssociatedTags = s.AssociatedTags
	o.CloudAccountID = s.CloudAccountID
	o.CreateIdempotencyKey = s.CreateIdempotencyKey
	o.CreateTime = s.CreateTime
	o.FirewallResource = s.FirewallResource
	o.Namespace = s.Namespace
	o.NormalizedTags = s.NormalizedTags
	o.Protected = s.Protected
	o.TenantID = s.TenantID
	o.Timestamp = s.Timestamp
	o.UpdateIdempotencyKey = s.UpdateIdempotencyKey
	o.UpdateTime = s.UpdateTime
	o.ZHash = s.ZHash
	o.Zone = s.Zone

	return nil
}

// Version returns the hardcoded version of the model.
func (o *FirewallLicensingCredits) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *FirewallLicensingCredits) BleveType() string {

	return "firewalllicensingcredits"
}

// DefaultOrder returns the list of default ordering fields.
func (o *FirewallLicensingCredits) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *FirewallLicensingCredits) Doc() string {

	return `Represents firewall licensing credits.`
}

func (o *FirewallLicensingCredits) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetAnnotations returns the Annotations of the receiver.
func (o *FirewallLicensingCredits) GetAnnotations() map[string][]string {

	return o.Annotations
}

// SetAnnotations sets the property Annotations of the receiver using the given value.
func (o *FirewallLicensingCredits) SetAnnotations(annotations map[string][]string) {

	o.Annotations = annotations
}

// GetAssociatedTags returns the AssociatedTags of the receiver.
func (o *FirewallLicensingCredits) GetAssociatedTags() []string {

	return o.AssociatedTags
}

// SetAssociatedTags sets the property AssociatedTags of the receiver using the given value.
func (o *FirewallLicensingCredits) SetAssociatedTags(associatedTags []string) {

	o.AssociatedTags = associatedTags
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *FirewallLicensingCredits) GetCreateTime() time.Time {

	return o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the given value.
func (o *FirewallLicensingCredits) SetCreateTime(createTime time.Time) {

	o.CreateTime = createTime
}

// GetNamespace returns the Namespace of the receiver.
func (o *FirewallLicensingCredits) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *FirewallLicensingCredits) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// GetNormalizedTags returns the NormalizedTags of the receiver.
func (o *FirewallLicensingCredits) GetNormalizedTags() []string {

	return o.NormalizedTags
}

// SetNormalizedTags sets the property NormalizedTags of the receiver using the given value.
func (o *FirewallLicensingCredits) SetNormalizedTags(normalizedTags []string) {

	o.NormalizedTags = normalizedTags
}

// GetProtected returns the Protected of the receiver.
func (o *FirewallLicensingCredits) GetProtected() bool {

	return o.Protected
}

// SetProtected sets the property Protected of the receiver using the given value.
func (o *FirewallLicensingCredits) SetProtected(protected bool) {

	o.Protected = protected
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *FirewallLicensingCredits) GetUpdateTime() time.Time {

	return o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the given value.
func (o *FirewallLicensingCredits) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = updateTime
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *FirewallLicensingCredits) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseFirewallLicensingCredits{
			EnhancedSupportCredits: &o.EnhancedSupportCredits,
			FWUsageCredits:         &o.FWUsageCredits,
			ID:                     &o.ID,
			PrismaCloudCredits:     &o.PrismaCloudCredits,
			TPUsageCredits:         &o.TPUsageCredits,
			TrafficSecuredCredits:  &o.TrafficSecuredCredits,
			URLFUsageCredits:       &o.URLFUsageCredits,
			Annotations:            &o.Annotations,
			AssociatedTags:         &o.AssociatedTags,
			CloudAccountID:         &o.CloudAccountID,
			CreateIdempotencyKey:   &o.CreateIdempotencyKey,
			CreateTime:             &o.CreateTime,
			FirewallResource:       &o.FirewallResource,
			Namespace:              &o.Namespace,
			NormalizedTags:         &o.NormalizedTags,
			Protected:              &o.Protected,
			TenantID:               &o.TenantID,
			Timestamp:              &o.Timestamp,
			UpdateIdempotencyKey:   &o.UpdateIdempotencyKey,
			UpdateTime:             &o.UpdateTime,
			ZHash:                  &o.ZHash,
			Zone:                   &o.Zone,
		}
	}

	sp := &SparseFirewallLicensingCredits{}
	for _, f := range fields {
		switch f {
		case "EnhancedSupportCredits":
			sp.EnhancedSupportCredits = &(o.EnhancedSupportCredits)
		case "FWUsageCredits":
			sp.FWUsageCredits = &(o.FWUsageCredits)
		case "ID":
			sp.ID = &(o.ID)
		case "PrismaCloudCredits":
			sp.PrismaCloudCredits = &(o.PrismaCloudCredits)
		case "TPUsageCredits":
			sp.TPUsageCredits = &(o.TPUsageCredits)
		case "TrafficSecuredCredits":
			sp.TrafficSecuredCredits = &(o.TrafficSecuredCredits)
		case "URLFUsageCredits":
			sp.URLFUsageCredits = &(o.URLFUsageCredits)
		case "annotations":
			sp.Annotations = &(o.Annotations)
		case "associatedTags":
			sp.AssociatedTags = &(o.AssociatedTags)
		case "cloudAccountID":
			sp.CloudAccountID = &(o.CloudAccountID)
		case "createIdempotencyKey":
			sp.CreateIdempotencyKey = &(o.CreateIdempotencyKey)
		case "createTime":
			sp.CreateTime = &(o.CreateTime)
		case "firewallResource":
			sp.FirewallResource = &(o.FirewallResource)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "normalizedTags":
			sp.NormalizedTags = &(o.NormalizedTags)
		case "protected":
			sp.Protected = &(o.Protected)
		case "tenantID":
			sp.TenantID = &(o.TenantID)
		case "timestamp":
			sp.Timestamp = &(o.Timestamp)
		case "updateIdempotencyKey":
			sp.UpdateIdempotencyKey = &(o.UpdateIdempotencyKey)
		case "updateTime":
			sp.UpdateTime = &(o.UpdateTime)
		case "zHash":
			sp.ZHash = &(o.ZHash)
		case "zone":
			sp.Zone = &(o.Zone)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseFirewallLicensingCredits to the object.
func (o *FirewallLicensingCredits) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseFirewallLicensingCredits)
	if so.EnhancedSupportCredits != nil {
		o.EnhancedSupportCredits = *so.EnhancedSupportCredits
	}
	if so.FWUsageCredits != nil {
		o.FWUsageCredits = *so.FWUsageCredits
	}
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.PrismaCloudCredits != nil {
		o.PrismaCloudCredits = *so.PrismaCloudCredits
	}
	if so.TPUsageCredits != nil {
		o.TPUsageCredits = *so.TPUsageCredits
	}
	if so.TrafficSecuredCredits != nil {
		o.TrafficSecuredCredits = *so.TrafficSecuredCredits
	}
	if so.URLFUsageCredits != nil {
		o.URLFUsageCredits = *so.URLFUsageCredits
	}
	if so.Annotations != nil {
		o.Annotations = *so.Annotations
	}
	if so.AssociatedTags != nil {
		o.AssociatedTags = *so.AssociatedTags
	}
	if so.CloudAccountID != nil {
		o.CloudAccountID = *so.CloudAccountID
	}
	if so.CreateIdempotencyKey != nil {
		o.CreateIdempotencyKey = *so.CreateIdempotencyKey
	}
	if so.CreateTime != nil {
		o.CreateTime = *so.CreateTime
	}
	if so.FirewallResource != nil {
		o.FirewallResource = *so.FirewallResource
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.NormalizedTags != nil {
		o.NormalizedTags = *so.NormalizedTags
	}
	if so.Protected != nil {
		o.Protected = *so.Protected
	}
	if so.TenantID != nil {
		o.TenantID = *so.TenantID
	}
	if so.Timestamp != nil {
		o.Timestamp = *so.Timestamp
	}
	if so.UpdateIdempotencyKey != nil {
		o.UpdateIdempotencyKey = *so.UpdateIdempotencyKey
	}
	if so.UpdateTime != nil {
		o.UpdateTime = *so.UpdateTime
	}
	if so.ZHash != nil {
		o.ZHash = *so.ZHash
	}
	if so.Zone != nil {
		o.Zone = *so.Zone
	}
}

// DeepCopy returns a deep copy if the FirewallLicensingCredits.
func (o *FirewallLicensingCredits) DeepCopy() *FirewallLicensingCredits {

	if o == nil {
		return nil
	}

	out := &FirewallLicensingCredits{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *FirewallLicensingCredits.
func (o *FirewallLicensingCredits) DeepCopyInto(out *FirewallLicensingCredits) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy FirewallLicensingCredits: %s", err))
	}

	*out = *target.(*FirewallLicensingCredits)
}

// Validate valides the current information stored into the structure.
func (o *FirewallLicensingCredits) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := ValidateTagsWithoutReservedPrefixes("associatedTags", o.AssociatedTags); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateRequiredString("cloudAccountID", o.CloudAccountID); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredString("firewallResource", o.FirewallResource); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredString("tenantID", o.TenantID); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredTime("timestamp", o.Timestamp); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*FirewallLicensingCredits) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := FirewallLicensingCreditsAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return FirewallLicensingCreditsLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*FirewallLicensingCredits) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return FirewallLicensingCreditsAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *FirewallLicensingCredits) ValueForAttribute(name string) any {

	switch name {
	case "EnhancedSupportCredits":
		return o.EnhancedSupportCredits
	case "FWUsageCredits":
		return o.FWUsageCredits
	case "ID":
		return o.ID
	case "PrismaCloudCredits":
		return o.PrismaCloudCredits
	case "TPUsageCredits":
		return o.TPUsageCredits
	case "TrafficSecuredCredits":
		return o.TrafficSecuredCredits
	case "URLFUsageCredits":
		return o.URLFUsageCredits
	case "annotations":
		return o.Annotations
	case "associatedTags":
		return o.AssociatedTags
	case "cloudAccountID":
		return o.CloudAccountID
	case "createIdempotencyKey":
		return o.CreateIdempotencyKey
	case "createTime":
		return o.CreateTime
	case "firewallResource":
		return o.FirewallResource
	case "namespace":
		return o.Namespace
	case "normalizedTags":
		return o.NormalizedTags
	case "protected":
		return o.Protected
	case "tenantID":
		return o.TenantID
	case "timestamp":
		return o.Timestamp
	case "updateIdempotencyKey":
		return o.UpdateIdempotencyKey
	case "updateTime":
		return o.UpdateTime
	case "zHash":
		return o.ZHash
	case "zone":
		return o.Zone
	}

	return nil
}

// FirewallLicensingCreditsAttributesMap represents the map of attribute for FirewallLicensingCredits.
var FirewallLicensingCreditsAttributesMap = map[string]elemental.AttributeSpecification{
	"EnhancedSupportCredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "enhancedsupportcredits",
		ConvertedName:  "EnhancedSupportCredits",
		Description:    `Represents enhanced support credits.`,
		Exposed:        true,
		Name:           "EnhancedSupportCredits",
		Stored:         true,
		Type:           "integer",
	},
	"FWUsageCredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "fwusagecredits",
		ConvertedName:  "FWUsageCredits",
		Description:    `Represents firewall usage credits.`,
		Exposed:        true,
		Name:           "FWUsageCredits",
		Stored:         true,
		Type:           "integer",
	},
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `Identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"PrismaCloudCredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "prismacloudcredits",
		ConvertedName:  "PrismaCloudCredits",
		Description:    `Represents Prisma Cloud management credits.`,
		Exposed:        true,
		Name:           "PrismaCloudCredits",
		Stored:         true,
		Type:           "integer",
	},
	"TPUsageCredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "tpusagecredits",
		ConvertedName:  "TPUsageCredits",
		Description:    `Represents threat prevention usage credits.`,
		Exposed:        true,
		Name:           "TPUsageCredits",
		Stored:         true,
		Type:           "integer",
	},
	"TrafficSecuredCredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "trafficsecuredcredits",
		ConvertedName:  "TrafficSecuredCredits",
		Description:    `Represents traffic secured usage credits.`,
		Exposed:        true,
		Name:           "TrafficSecuredCredits",
		Stored:         true,
		Type:           "integer",
	},
	"URLFUsageCredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "urlfusagecredits",
		ConvertedName:  "URLFUsageCredits",
		Description:    `Represents URL filtering usage credits.`,
		Exposed:        true,
		Name:           "URLFUsageCredits",
		Stored:         true,
		Type:           "integer",
	},
	"Annotations": {
		AllowedChoices: []string{},
		BSONFieldName:  "annotations",
		ConvertedName:  "Annotations",
		Description:    `Stores additional information about an entity.`,
		Exposed:        true,
		Getter:         true,
		Name:           "annotations",
		Setter:         true,
		Stored:         true,
		SubType:        "map[string][]string",
		Type:           "external",
	},
	"AssociatedTags": {
		AllowedChoices: []string{},
		BSONFieldName:  "associatedtags",
		ConvertedName:  "AssociatedTags",
		Description:    `List of tags attached to an entity.`,
		Exposed:        true,
		Getter:         true,
		Name:           "associatedTags",
		Setter:         true,
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"CloudAccountID": {
		AllowedChoices: []string{},
		BSONFieldName:  "cloudaccountid",
		ConvertedName:  "CloudAccountID",
		Description:    `Represents the user cloud account ID.`,
		Exposed:        true,
		Name:           "cloudAccountID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},

	"CreateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"FirewallResource": {
		AllowedChoices: []string{},
		BSONFieldName:  "firewallresource",
		ConvertedName:  "FirewallResource",
		Description:    `Represents firewall resource.`,
		Exposed:        true,
		Name:           "firewallResource",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `Namespace tag attached to an entity.`,
		Exposed:        true,
		Filterable:     true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"NormalizedTags": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "normalizedtags",
		ConvertedName:  "NormalizedTags",
		Description:    `Contains the list of normalized tags of the entities.`,
		Exposed:        true,
		Getter:         true,
		Name:           "normalizedTags",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		SubType:        "string",
		Transient:      true,
		Type:           "list",
	},
	"Protected": {
		AllowedChoices: []string{},
		BSONFieldName:  "protected",
		ConvertedName:  "Protected",
		Description:    `Defines if the object is protected.`,
		Exposed:        true,
		Getter:         true,
		Name:           "protected",
		Orderable:      true,
		Setter:         true,
		Stored:         true,
		Type:           "boolean",
	},
	"TenantID": {
		AllowedChoices: []string{},
		BSONFieldName:  "tenantid",
		ConvertedName:  "TenantID",
		Description:    `Represents the cloud ngfw tenant ID.`,
		Exposed:        true,
		Name:           "tenantID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"Timestamp": {
		AllowedChoices: []string{},
		BSONFieldName:  "timestamp",
		ConvertedName:  "Timestamp",
		Description:    `The timestamp of this record.`,
		Exposed:        true,
		Name:           "timestamp",
		Required:       true,
		Stored:         true,
		Type:           "time",
	},

	"UpdateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
}

// FirewallLicensingCreditsLowerCaseAttributesMap represents the map of attribute for FirewallLicensingCredits.
var FirewallLicensingCreditsLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"enhancedsupportcredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "enhancedsupportcredits",
		ConvertedName:  "EnhancedSupportCredits",
		Description:    `Represents enhanced support credits.`,
		Exposed:        true,
		Name:           "EnhancedSupportCredits",
		Stored:         true,
		Type:           "integer",
	},
	"fwusagecredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "fwusagecredits",
		ConvertedName:  "FWUsageCredits",
		Description:    `Represents firewall usage credits.`,
		Exposed:        true,
		Name:           "FWUsageCredits",
		Stored:         true,
		Type:           "integer",
	},
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `Identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"prismacloudcredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "prismacloudcredits",
		ConvertedName:  "PrismaCloudCredits",
		Description:    `Represents Prisma Cloud management credits.`,
		Exposed:        true,
		Name:           "PrismaCloudCredits",
		Stored:         true,
		Type:           "integer",
	},
	"tpusagecredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "tpusagecredits",
		ConvertedName:  "TPUsageCredits",
		Description:    `Represents threat prevention usage credits.`,
		Exposed:        true,
		Name:           "TPUsageCredits",
		Stored:         true,
		Type:           "integer",
	},
	"trafficsecuredcredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "trafficsecuredcredits",
		ConvertedName:  "TrafficSecuredCredits",
		Description:    `Represents traffic secured usage credits.`,
		Exposed:        true,
		Name:           "TrafficSecuredCredits",
		Stored:         true,
		Type:           "integer",
	},
	"urlfusagecredits": {
		AllowedChoices: []string{},
		BSONFieldName:  "urlfusagecredits",
		ConvertedName:  "URLFUsageCredits",
		Description:    `Represents URL filtering usage credits.`,
		Exposed:        true,
		Name:           "URLFUsageCredits",
		Stored:         true,
		Type:           "integer",
	},
	"annotations": {
		AllowedChoices: []string{},
		BSONFieldName:  "annotations",
		ConvertedName:  "Annotations",
		Description:    `Stores additional information about an entity.`,
		Exposed:        true,
		Getter:         true,
		Name:           "annotations",
		Setter:         true,
		Stored:         true,
		SubType:        "map[string][]string",
		Type:           "external",
	},
	"associatedtags": {
		AllowedChoices: []string{},
		BSONFieldName:  "associatedtags",
		ConvertedName:  "AssociatedTags",
		Description:    `List of tags attached to an entity.`,
		Exposed:        true,
		Getter:         true,
		Name:           "associatedTags",
		Setter:         true,
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"cloudaccountid": {
		AllowedChoices: []string{},
		BSONFieldName:  "cloudaccountid",
		ConvertedName:  "CloudAccountID",
		Description:    `Represents the user cloud account ID.`,
		Exposed:        true,
		Name:           "cloudAccountID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},

	"createtime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"firewallresource": {
		AllowedChoices: []string{},
		BSONFieldName:  "firewallresource",
		ConvertedName:  "FirewallResource",
		Description:    `Represents firewall resource.`,
		Exposed:        true,
		Name:           "firewallResource",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `Namespace tag attached to an entity.`,
		Exposed:        true,
		Filterable:     true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"normalizedtags": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "normalizedtags",
		ConvertedName:  "NormalizedTags",
		Description:    `Contains the list of normalized tags of the entities.`,
		Exposed:        true,
		Getter:         true,
		Name:           "normalizedTags",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		SubType:        "string",
		Transient:      true,
		Type:           "list",
	},
	"protected": {
		AllowedChoices: []string{},
		BSONFieldName:  "protected",
		ConvertedName:  "Protected",
		Description:    `Defines if the object is protected.`,
		Exposed:        true,
		Getter:         true,
		Name:           "protected",
		Orderable:      true,
		Setter:         true,
		Stored:         true,
		Type:           "boolean",
	},
	"tenantid": {
		AllowedChoices: []string{},
		BSONFieldName:  "tenantid",
		ConvertedName:  "TenantID",
		Description:    `Represents the cloud ngfw tenant ID.`,
		Exposed:        true,
		Name:           "tenantID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"timestamp": {
		AllowedChoices: []string{},
		BSONFieldName:  "timestamp",
		ConvertedName:  "Timestamp",
		Description:    `The timestamp of this record.`,
		Exposed:        true,
		Name:           "timestamp",
		Required:       true,
		Stored:         true,
		Type:           "time",
	},

	"updatetime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
}

// SparseFirewallLicensingCreditsList represents a list of SparseFirewallLicensingCredits
type SparseFirewallLicensingCreditsList []*SparseFirewallLicensingCredits

// Identity returns the identity of the objects in the list.
func (o SparseFirewallLicensingCreditsList) Identity() elemental.Identity {

	return FirewallLicensingCreditsIdentity
}

// Copy returns a pointer to a copy the SparseFirewallLicensingCreditsList.
func (o SparseFirewallLicensingCreditsList) Copy() elemental.Identifiables {

	copy := append(SparseFirewallLicensingCreditsList{}, o...)
	return &copy
}

// Append appends the objects to the a new copy of the SparseFirewallLicensingCreditsList.
func (o SparseFirewallLicensingCreditsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(SparseFirewallLicensingCreditsList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*SparseFirewallLicensingCredits))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseFirewallLicensingCreditsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseFirewallLicensingCreditsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseFirewallLicensingCreditsList converted to FirewallLicensingCreditsList.
func (o SparseFirewallLicensingCreditsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseFirewallLicensingCreditsList) Version() int {

	return 1
}

// SparseFirewallLicensingCredits represents the sparse version of a firewalllicensingcredits.
type SparseFirewallLicensingCredits struct {
	// Represents enhanced support credits.
	EnhancedSupportCredits *int `json:"EnhancedSupportCredits,omitempty" msgpack:"EnhancedSupportCredits,omitempty" bson:"enhancedsupportcredits,omitempty" mapstructure:"EnhancedSupportCredits,omitempty"`

	// Represents firewall usage credits.
	FWUsageCredits *int `json:"FWUsageCredits,omitempty" msgpack:"FWUsageCredits,omitempty" bson:"fwusagecredits,omitempty" mapstructure:"FWUsageCredits,omitempty"`

	// Identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Represents Prisma Cloud management credits.
	PrismaCloudCredits *int `json:"PrismaCloudCredits,omitempty" msgpack:"PrismaCloudCredits,omitempty" bson:"prismacloudcredits,omitempty" mapstructure:"PrismaCloudCredits,omitempty"`

	// Represents threat prevention usage credits.
	TPUsageCredits *int `json:"TPUsageCredits,omitempty" msgpack:"TPUsageCredits,omitempty" bson:"tpusagecredits,omitempty" mapstructure:"TPUsageCredits,omitempty"`

	// Represents traffic secured usage credits.
	TrafficSecuredCredits *int `json:"TrafficSecuredCredits,omitempty" msgpack:"TrafficSecuredCredits,omitempty" bson:"trafficsecuredcredits,omitempty" mapstructure:"TrafficSecuredCredits,omitempty"`

	// Represents URL filtering usage credits.
	URLFUsageCredits *int `json:"URLFUsageCredits,omitempty" msgpack:"URLFUsageCredits,omitempty" bson:"urlfusagecredits,omitempty" mapstructure:"URLFUsageCredits,omitempty"`

	// Stores additional information about an entity.
	Annotations *map[string][]string `json:"annotations,omitempty" msgpack:"annotations,omitempty" bson:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// List of tags attached to an entity.
	AssociatedTags *[]string `json:"associatedTags,omitempty" msgpack:"associatedTags,omitempty" bson:"associatedtags,omitempty" mapstructure:"associatedTags,omitempty"`

	// Represents the user cloud account ID.
	CloudAccountID *string `json:"cloudAccountID,omitempty" msgpack:"cloudAccountID,omitempty" bson:"cloudaccountid,omitempty" mapstructure:"cloudAccountID,omitempty"`

	// internal idempotency key for a create operation.
	CreateIdempotencyKey *string `json:"-" msgpack:"-" bson:"createidempotencykey,omitempty" mapstructure:"-,omitempty"`

	// Creation date of the object.
	CreateTime *time.Time `json:"createTime,omitempty" msgpack:"createTime,omitempty" bson:"createtime,omitempty" mapstructure:"createTime,omitempty"`

	// Represents firewall resource.
	FirewallResource *string `json:"firewallResource,omitempty" msgpack:"firewallResource,omitempty" bson:"firewallresource,omitempty" mapstructure:"firewallResource,omitempty"`

	// Namespace tag attached to an entity.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Contains the list of normalized tags of the entities.
	NormalizedTags *[]string `json:"normalizedTags,omitempty" msgpack:"normalizedTags,omitempty" bson:"normalizedtags,omitempty" mapstructure:"normalizedTags,omitempty"`

	// Defines if the object is protected.
	Protected *bool `json:"protected,omitempty" msgpack:"protected,omitempty" bson:"protected,omitempty" mapstructure:"protected,omitempty"`

	// Represents the cloud ngfw tenant ID.
	TenantID *string `json:"tenantID,omitempty" msgpack:"tenantID,omitempty" bson:"tenantid,omitempty" mapstructure:"tenantID,omitempty"`

	// The timestamp of this record.
	Timestamp *time.Time `json:"timestamp,omitempty" msgpack:"timestamp,omitempty" bson:"timestamp,omitempty" mapstructure:"timestamp,omitempty"`

	// internal idempotency key for a update operation.
	UpdateIdempotencyKey *string `json:"-" msgpack:"-" bson:"updateidempotencykey,omitempty" mapstructure:"-,omitempty"`

	// Last update date of the object.
	UpdateTime *time.Time `json:"updateTime,omitempty" msgpack:"updateTime,omitempty" bson:"updatetime,omitempty" mapstructure:"updateTime,omitempty"`

	// geographical hash of the data. This is used for sharding and
	// georedundancy.
	ZHash *int `json:"-" msgpack:"-" bson:"zhash,omitempty" mapstructure:"-,omitempty"`

	// Logical storage zone. Used for sharding.
	Zone *int `json:"-" msgpack:"-" bson:"zone,omitempty" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseFirewallLicensingCredits returns a new  SparseFirewallLicensingCredits.
func NewSparseFirewallLicensingCredits() *SparseFirewallLicensingCredits {
	return &SparseFirewallLicensingCredits{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseFirewallLicensingCredits) Identity() elemental.Identity {

	return FirewallLicensingCreditsIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseFirewallLicensingCredits) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseFirewallLicensingCredits) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseFirewallLicensingCredits) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseFirewallLicensingCredits{}

	if o.EnhancedSupportCredits != nil {
		s.EnhancedSupportCredits = o.EnhancedSupportCredits
	}
	if o.FWUsageCredits != nil {
		s.FWUsageCredits = o.FWUsageCredits
	}
	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.PrismaCloudCredits != nil {
		s.PrismaCloudCredits = o.PrismaCloudCredits
	}
	if o.TPUsageCredits != nil {
		s.TPUsageCredits = o.TPUsageCredits
	}
	if o.TrafficSecuredCredits != nil {
		s.TrafficSecuredCredits = o.TrafficSecuredCredits
	}
	if o.URLFUsageCredits != nil {
		s.URLFUsageCredits = o.URLFUsageCredits
	}
	if o.Annotations != nil {
		s.Annotations = o.Annotations
	}
	if o.AssociatedTags != nil {
		s.AssociatedTags = o.AssociatedTags
	}
	if o.CloudAccountID != nil {
		s.CloudAccountID = o.CloudAccountID
	}
	if o.CreateIdempotencyKey != nil {
		s.CreateIdempotencyKey = o.CreateIdempotencyKey
	}
	if o.CreateTime != nil {
		s.CreateTime = o.CreateTime
	}
	if o.FirewallResource != nil {
		s.FirewallResource = o.FirewallResource
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.NormalizedTags != nil {
		s.NormalizedTags = o.NormalizedTags
	}
	if o.Protected != nil {
		s.Protected = o.Protected
	}
	if o.TenantID != nil {
		s.TenantID = o.TenantID
	}
	if o.Timestamp != nil {
		s.Timestamp = o.Timestamp
	}
	if o.UpdateIdempotencyKey != nil {
		s.UpdateIdempotencyKey = o.UpdateIdempotencyKey
	}
	if o.UpdateTime != nil {
		s.UpdateTime = o.UpdateTime
	}
	if o.ZHash != nil {
		s.ZHash = o.ZHash
	}
	if o.Zone != nil {
		s.Zone = o.Zone
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseFirewallLicensingCredits) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseFirewallLicensingCredits{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	if s.EnhancedSupportCredits != nil {
		o.EnhancedSupportCredits = s.EnhancedSupportCredits
	}
	if s.FWUsageCredits != nil {
		o.FWUsageCredits = s.FWUsageCredits
	}
	id := s.ID.Hex()
	o.ID = &id
	if s.PrismaCloudCredits != nil {
		o.PrismaCloudCredits = s.PrismaCloudCredits
	}
	if s.TPUsageCredits != nil {
		o.TPUsageCredits = s.TPUsageCredits
	}
	if s.TrafficSecuredCredits != nil {
		o.TrafficSecuredCredits = s.TrafficSecuredCredits
	}
	if s.URLFUsageCredits != nil {
		o.URLFUsageCredits = s.URLFUsageCredits
	}
	if s.Annotations != nil {
		o.Annotations = s.Annotations
	}
	if s.AssociatedTags != nil {
		o.AssociatedTags = s.AssociatedTags
	}
	if s.CloudAccountID != nil {
		o.CloudAccountID = s.CloudAccountID
	}
	if s.CreateIdempotencyKey != nil {
		o.CreateIdempotencyKey = s.CreateIdempotencyKey
	}
	if s.CreateTime != nil {
		o.CreateTime = s.CreateTime
	}
	if s.FirewallResource != nil {
		o.FirewallResource = s.FirewallResource
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.NormalizedTags != nil {
		o.NormalizedTags = s.NormalizedTags
	}
	if s.Protected != nil {
		o.Protected = s.Protected
	}
	if s.TenantID != nil {
		o.TenantID = s.TenantID
	}
	if s.Timestamp != nil {
		o.Timestamp = s.Timestamp
	}
	if s.UpdateIdempotencyKey != nil {
		o.UpdateIdempotencyKey = s.UpdateIdempotencyKey
	}
	if s.UpdateTime != nil {
		o.UpdateTime = s.UpdateTime
	}
	if s.ZHash != nil {
		o.ZHash = s.ZHash
	}
	if s.Zone != nil {
		o.Zone = s.Zone
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseFirewallLicensingCredits) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseFirewallLicensingCredits) ToPlain() elemental.PlainIdentifiable {

	out := NewFirewallLicensingCredits()
	if o.EnhancedSupportCredits != nil {
		out.EnhancedSupportCredits = *o.EnhancedSupportCredits
	}
	if o.FWUsageCredits != nil {
		out.FWUsageCredits = *o.FWUsageCredits
	}
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.PrismaCloudCredits != nil {
		out.PrismaCloudCredits = *o.PrismaCloudCredits
	}
	if o.TPUsageCredits != nil {
		out.TPUsageCredits = *o.TPUsageCredits
	}
	if o.TrafficSecuredCredits != nil {
		out.TrafficSecuredCredits = *o.TrafficSecuredCredits
	}
	if o.URLFUsageCredits != nil {
		out.URLFUsageCredits = *o.URLFUsageCredits
	}
	if o.Annotations != nil {
		out.Annotations = *o.Annotations
	}
	if o.AssociatedTags != nil {
		out.AssociatedTags = *o.AssociatedTags
	}
	if o.CloudAccountID != nil {
		out.CloudAccountID = *o.CloudAccountID
	}
	if o.CreateIdempotencyKey != nil {
		out.CreateIdempotencyKey = *o.CreateIdempotencyKey
	}
	if o.CreateTime != nil {
		out.CreateTime = *o.CreateTime
	}
	if o.FirewallResource != nil {
		out.FirewallResource = *o.FirewallResource
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.NormalizedTags != nil {
		out.NormalizedTags = *o.NormalizedTags
	}
	if o.Protected != nil {
		out.Protected = *o.Protected
	}
	if o.TenantID != nil {
		out.TenantID = *o.TenantID
	}
	if o.Timestamp != nil {
		out.Timestamp = *o.Timestamp
	}
	if o.UpdateIdempotencyKey != nil {
		out.UpdateIdempotencyKey = *o.UpdateIdempotencyKey
	}
	if o.UpdateTime != nil {
		out.UpdateTime = *o.UpdateTime
	}
	if o.ZHash != nil {
		out.ZHash = *o.ZHash
	}
	if o.Zone != nil {
		out.Zone = *o.Zone
	}

	return out
}

// GetAnnotations returns the Annotations of the receiver.
func (o *SparseFirewallLicensingCredits) GetAnnotations() (out map[string][]string) {

	if o.Annotations == nil {
		return
	}

	return *o.Annotations
}

// SetAnnotations sets the property Annotations of the receiver using the address of the given value.
func (o *SparseFirewallLicensingCredits) SetAnnotations(annotations map[string][]string) {

	o.Annotations = &annotations
}

// GetAssociatedTags returns the AssociatedTags of the receiver.
func (o *SparseFirewallLicensingCredits) GetAssociatedTags() (out []string) {

	if o.AssociatedTags == nil {
		return
	}

	return *o.AssociatedTags
}

// SetAssociatedTags sets the property AssociatedTags of the receiver using the address of the given value.
func (o *SparseFirewallLicensingCredits) SetAssociatedTags(associatedTags []string) {

	o.AssociatedTags = &associatedTags
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *SparseFirewallLicensingCredits) GetCreateTime() (out time.Time) {

	if o.CreateTime == nil {
		return
	}

	return *o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the address of the given value.
func (o *SparseFirewallLicensingCredits) SetCreateTime(createTime time.Time) {

	o.CreateTime = &createTime
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseFirewallLicensingCredits) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseFirewallLicensingCredits) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// GetNormalizedTags returns the NormalizedTags of the receiver.
func (o *SparseFirewallLicensingCredits) GetNormalizedTags() (out []string) {

	if o.NormalizedTags == nil {
		return
	}

	return *o.NormalizedTags
}

// SetNormalizedTags sets the property NormalizedTags of the receiver using the address of the given value.
func (o *SparseFirewallLicensingCredits) SetNormalizedTags(normalizedTags []string) {

	o.NormalizedTags = &normalizedTags
}

// GetProtected returns the Protected of the receiver.
func (o *SparseFirewallLicensingCredits) GetProtected() (out bool) {

	if o.Protected == nil {
		return
	}

	return *o.Protected
}

// SetProtected sets the property Protected of the receiver using the address of the given value.
func (o *SparseFirewallLicensingCredits) SetProtected(protected bool) {

	o.Protected = &protected
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *SparseFirewallLicensingCredits) GetUpdateTime() (out time.Time) {

	if o.UpdateTime == nil {
		return
	}

	return *o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the address of the given value.
func (o *SparseFirewallLicensingCredits) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = &updateTime
}

// DeepCopy returns a deep copy if the SparseFirewallLicensingCredits.
func (o *SparseFirewallLicensingCredits) DeepCopy() *SparseFirewallLicensingCredits {

	if o == nil {
		return nil
	}

	out := &SparseFirewallLicensingCredits{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseFirewallLicensingCredits.
func (o *SparseFirewallLicensingCredits) DeepCopyInto(out *SparseFirewallLicensingCredits) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseFirewallLicensingCredits: %s", err))
	}

	*out = *target.(*SparseFirewallLicensingCredits)
}

type mongoAttributesFirewallLicensingCredits struct {
	EnhancedSupportCredits int                 `bson:"enhancedsupportcredits"`
	FWUsageCredits         int                 `bson:"fwusagecredits"`
	ID                     bson.ObjectId       `bson:"_id,omitempty"`
	PrismaCloudCredits     int                 `bson:"prismacloudcredits"`
	TPUsageCredits         int                 `bson:"tpusagecredits"`
	TrafficSecuredCredits  int                 `bson:"trafficsecuredcredits"`
	URLFUsageCredits       int                 `bson:"urlfusagecredits"`
	Annotations            map[string][]string `bson:"annotations"`
	AssociatedTags         []string            `bson:"associatedtags"`
	CloudAccountID         string              `bson:"cloudaccountid"`
	CreateIdempotencyKey   string              `bson:"createidempotencykey"`
	CreateTime             time.Time           `bson:"createtime"`
	FirewallResource       string              `bson:"firewallresource"`
	Namespace              string              `bson:"namespace"`
	NormalizedTags         []string            `bson:"normalizedtags"`
	Protected              bool                `bson:"protected"`
	TenantID               string              `bson:"tenantid"`
	Timestamp              time.Time           `bson:"timestamp"`
	UpdateIdempotencyKey   string              `bson:"updateidempotencykey"`
	UpdateTime             time.Time           `bson:"updatetime"`
	ZHash                  int                 `bson:"zhash"`
	Zone                   int                 `bson:"zone"`
}
type mongoAttributesSparseFirewallLicensingCredits struct {
	EnhancedSupportCredits *int                 `bson:"enhancedsupportcredits,omitempty"`
	FWUsageCredits         *int                 `bson:"fwusagecredits,omitempty"`
	ID                     bson.ObjectId        `bson:"_id,omitempty"`
	PrismaCloudCredits     *int                 `bson:"prismacloudcredits,omitempty"`
	TPUsageCredits         *int                 `bson:"tpusagecredits,omitempty"`
	TrafficSecuredCredits  *int                 `bson:"trafficsecuredcredits,omitempty"`
	URLFUsageCredits       *int                 `bson:"urlfusagecredits,omitempty"`
	Annotations            *map[string][]string `bson:"annotations,omitempty"`
	AssociatedTags         *[]string            `bson:"associatedtags,omitempty"`
	CloudAccountID         *string              `bson:"cloudaccountid,omitempty"`
	CreateIdempotencyKey   *string              `bson:"createidempotencykey,omitempty"`
	CreateTime             *time.Time           `bson:"createtime,omitempty"`
	FirewallResource       *string              `bson:"firewallresource,omitempty"`
	Namespace              *string              `bson:"namespace,omitempty"`
	NormalizedTags         *[]string            `bson:"normalizedtags,omitempty"`
	Protected              *bool                `bson:"protected,omitempty"`
	TenantID               *string              `bson:"tenantid,omitempty"`
	Timestamp              *time.Time           `bson:"timestamp,omitempty"`
	UpdateIdempotencyKey   *string              `bson:"updateidempotencykey,omitempty"`
	UpdateTime             *time.Time           `bson:"updatetime,omitempty"`
	ZHash                  *int                 `bson:"zhash,omitempty"`
	Zone                   *int                 `bson:"zone,omitempty"`
}
