// Code generated by elegen. DO NOT EDIT.
// Source: go.aporeto.io/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"time"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.aporeto.io/elemental"
)

// FirewallCommittedRulesetObjectTypeValue represents the possible values for attribute "objectType".
type FirewallCommittedRulesetObjectTypeValue string

const (
	// FirewallCommittedRulesetObjectTypeFirewallRuleset represents the value FirewallRuleset.
	FirewallCommittedRulesetObjectTypeFirewallRuleset FirewallCommittedRulesetObjectTypeValue = "FirewallRuleset"

	// FirewallCommittedRulesetObjectTypeFirewallTemplate represents the value FirewallTemplate.
	FirewallCommittedRulesetObjectTypeFirewallTemplate FirewallCommittedRulesetObjectTypeValue = "FirewallTemplate"
)

// FirewallCommittedRulesetIdentity represents the Identity of the object.
var FirewallCommittedRulesetIdentity = elemental.Identity{
	Name:     "firewallcommittedruleset",
	Category: "firewallcommittedrulesets",
	Package:  "ngfw",
	Private:  false,
}

// FirewallCommittedRulesetsList represents a list of FirewallCommittedRulesets
type FirewallCommittedRulesetsList []*FirewallCommittedRuleset

// Identity returns the identity of the objects in the list.
func (o FirewallCommittedRulesetsList) Identity() elemental.Identity {

	return FirewallCommittedRulesetIdentity
}

// Copy returns a pointer to a copy the FirewallCommittedRulesetsList.
func (o FirewallCommittedRulesetsList) Copy() elemental.Identifiables {

	out := append(FirewallCommittedRulesetsList{}, o...)
	return &out
}

// Append appends the objects to the a new copy of the FirewallCommittedRulesetsList.
func (o FirewallCommittedRulesetsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(FirewallCommittedRulesetsList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*FirewallCommittedRuleset))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o FirewallCommittedRulesetsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o FirewallCommittedRulesetsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the FirewallCommittedRulesetsList converted to SparseFirewallCommittedRulesetsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o FirewallCommittedRulesetsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseFirewallCommittedRulesetsList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToSparse(fields...).(*SparseFirewallCommittedRuleset)
	}

	return out
}

// Version returns the version of the content.
func (o FirewallCommittedRulesetsList) Version() int {

	return 1
}

// FirewallCommittedRuleset represents the model of a firewallcommittedruleset
type FirewallCommittedRuleset struct {
	// Identifier of the object.
	ID string `json:"ID" msgpack:"ID" bson:"-" mapstructure:"ID,omitempty"`

	// Stores additional information about an entity.
	Annotations map[string][]string `json:"annotations" msgpack:"annotations" bson:"annotations" mapstructure:"annotations,omitempty"`

	// List of tags attached to an entity.
	AssociatedTags []string `json:"associatedTags" msgpack:"associatedTags" bson:"associatedtags" mapstructure:"associatedTags,omitempty"`

	// The date when the ruleset or template was committed.
	CommittedTime time.Time `json:"committedTime" msgpack:"committedTime" bson:"committedtime" mapstructure:"committedTime,omitempty"`

	// internal idempotency key for a create operation.
	CreateIdempotencyKey string `json:"-" msgpack:"-" bson:"createidempotencykey" mapstructure:"-,omitempty"`

	// Creation date of the object.
	CreateTime time.Time `json:"createTime" msgpack:"createTime" bson:"createtime" mapstructure:"createTime,omitempty"`

	// Namespace tag attached to an entity.
	Namespace string `json:"namespace" msgpack:"namespace" bson:"namespace" mapstructure:"namespace,omitempty"`

	// Contains the list of normalized tags of the entities.
	NormalizedTags []string `json:"normalizedTags" msgpack:"normalizedTags" bson:"normalizedtags" mapstructure:"normalizedTags,omitempty"`

	// The ID of the ruleset or template that was committed.
	ObjectID time.Time `json:"objectID" msgpack:"objectID" bson:"objectid" mapstructure:"objectID,omitempty"`

	// The type of object committed.
	ObjectType FirewallCommittedRulesetObjectTypeValue `json:"objectType" msgpack:"objectType" bson:"objecttype" mapstructure:"objectType,omitempty"`

	// Defines if the object is protected.
	Protected bool `json:"protected" msgpack:"protected" bson:"protected" mapstructure:"protected,omitempty"`

	// internal idempotency key for a update operation.
	UpdateIdempotencyKey string `json:"-" msgpack:"-" bson:"updateidempotencykey" mapstructure:"-,omitempty"`

	// Last update date of the object.
	UpdateTime time.Time `json:"updateTime" msgpack:"updateTime" bson:"updatetime" mapstructure:"updateTime,omitempty"`

	// geographical hash of the data. This is used for sharding and
	// georedundancy.
	ZHash int `json:"-" msgpack:"-" bson:"zhash" mapstructure:"-,omitempty"`

	// Logical storage zone. Used for sharding.
	Zone int `json:"-" msgpack:"-" bson:"zone" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewFirewallCommittedRuleset returns a new *FirewallCommittedRuleset
func NewFirewallCommittedRuleset() *FirewallCommittedRuleset {

	return &FirewallCommittedRuleset{
		ModelVersion:   1,
		Annotations:    map[string][]string{},
		AssociatedTags: []string{},
		NormalizedTags: []string{},
		ObjectType:     FirewallCommittedRulesetObjectTypeFirewallRuleset,
	}
}

// Identity returns the Identity of the object.
func (o *FirewallCommittedRuleset) Identity() elemental.Identity {

	return FirewallCommittedRulesetIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *FirewallCommittedRuleset) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *FirewallCommittedRuleset) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *FirewallCommittedRuleset) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesFirewallCommittedRuleset{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.Annotations = o.Annotations
	s.AssociatedTags = o.AssociatedTags
	s.CommittedTime = o.CommittedTime
	s.CreateIdempotencyKey = o.CreateIdempotencyKey
	s.CreateTime = o.CreateTime
	s.Namespace = o.Namespace
	s.NormalizedTags = o.NormalizedTags
	s.ObjectID = o.ObjectID
	s.ObjectType = o.ObjectType
	s.Protected = o.Protected
	s.UpdateIdempotencyKey = o.UpdateIdempotencyKey
	s.UpdateTime = o.UpdateTime
	s.ZHash = o.ZHash
	s.Zone = o.Zone

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *FirewallCommittedRuleset) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesFirewallCommittedRuleset{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.Annotations = s.Annotations
	o.AssociatedTags = s.AssociatedTags
	o.CommittedTime = s.CommittedTime
	o.CreateIdempotencyKey = s.CreateIdempotencyKey
	o.CreateTime = s.CreateTime
	o.Namespace = s.Namespace
	o.NormalizedTags = s.NormalizedTags
	o.ObjectID = s.ObjectID
	o.ObjectType = s.ObjectType
	o.Protected = s.Protected
	o.UpdateIdempotencyKey = s.UpdateIdempotencyKey
	o.UpdateTime = s.UpdateTime
	o.ZHash = s.ZHash
	o.Zone = s.Zone

	return nil
}

// Version returns the hardcoded version of the model.
func (o *FirewallCommittedRuleset) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *FirewallCommittedRuleset) BleveType() string {

	return "firewallcommittedruleset"
}

// DefaultOrder returns the list of default ordering fields.
func (o *FirewallCommittedRuleset) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *FirewallCommittedRuleset) Doc() string {

	return `Represents a list of committed filewall rules.`
}

func (o *FirewallCommittedRuleset) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetAnnotations returns the Annotations of the receiver.
func (o *FirewallCommittedRuleset) GetAnnotations() map[string][]string {

	return o.Annotations
}

// SetAnnotations sets the property Annotations of the receiver using the given value.
func (o *FirewallCommittedRuleset) SetAnnotations(annotations map[string][]string) {

	o.Annotations = annotations
}

// GetAssociatedTags returns the AssociatedTags of the receiver.
func (o *FirewallCommittedRuleset) GetAssociatedTags() []string {

	return o.AssociatedTags
}

// SetAssociatedTags sets the property AssociatedTags of the receiver using the given value.
func (o *FirewallCommittedRuleset) SetAssociatedTags(associatedTags []string) {

	o.AssociatedTags = associatedTags
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *FirewallCommittedRuleset) GetCreateTime() time.Time {

	return o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the given value.
func (o *FirewallCommittedRuleset) SetCreateTime(createTime time.Time) {

	o.CreateTime = createTime
}

// GetNamespace returns the Namespace of the receiver.
func (o *FirewallCommittedRuleset) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *FirewallCommittedRuleset) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// GetNormalizedTags returns the NormalizedTags of the receiver.
func (o *FirewallCommittedRuleset) GetNormalizedTags() []string {

	return o.NormalizedTags
}

// SetNormalizedTags sets the property NormalizedTags of the receiver using the given value.
func (o *FirewallCommittedRuleset) SetNormalizedTags(normalizedTags []string) {

	o.NormalizedTags = normalizedTags
}

// GetProtected returns the Protected of the receiver.
func (o *FirewallCommittedRuleset) GetProtected() bool {

	return o.Protected
}

// SetProtected sets the property Protected of the receiver using the given value.
func (o *FirewallCommittedRuleset) SetProtected(protected bool) {

	o.Protected = protected
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *FirewallCommittedRuleset) GetUpdateTime() time.Time {

	return o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the given value.
func (o *FirewallCommittedRuleset) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = updateTime
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *FirewallCommittedRuleset) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseFirewallCommittedRuleset{
			ID:                   &o.ID,
			Annotations:          &o.Annotations,
			AssociatedTags:       &o.AssociatedTags,
			CommittedTime:        &o.CommittedTime,
			CreateIdempotencyKey: &o.CreateIdempotencyKey,
			CreateTime:           &o.CreateTime,
			Namespace:            &o.Namespace,
			NormalizedTags:       &o.NormalizedTags,
			ObjectID:             &o.ObjectID,
			ObjectType:           &o.ObjectType,
			Protected:            &o.Protected,
			UpdateIdempotencyKey: &o.UpdateIdempotencyKey,
			UpdateTime:           &o.UpdateTime,
			ZHash:                &o.ZHash,
			Zone:                 &o.Zone,
		}
	}

	sp := &SparseFirewallCommittedRuleset{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "annotations":
			sp.Annotations = &(o.Annotations)
		case "associatedTags":
			sp.AssociatedTags = &(o.AssociatedTags)
		case "committedTime":
			sp.CommittedTime = &(o.CommittedTime)
		case "createIdempotencyKey":
			sp.CreateIdempotencyKey = &(o.CreateIdempotencyKey)
		case "createTime":
			sp.CreateTime = &(o.CreateTime)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "normalizedTags":
			sp.NormalizedTags = &(o.NormalizedTags)
		case "objectID":
			sp.ObjectID = &(o.ObjectID)
		case "objectType":
			sp.ObjectType = &(o.ObjectType)
		case "protected":
			sp.Protected = &(o.Protected)
		case "updateIdempotencyKey":
			sp.UpdateIdempotencyKey = &(o.UpdateIdempotencyKey)
		case "updateTime":
			sp.UpdateTime = &(o.UpdateTime)
		case "zHash":
			sp.ZHash = &(o.ZHash)
		case "zone":
			sp.Zone = &(o.Zone)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseFirewallCommittedRuleset to the object.
func (o *FirewallCommittedRuleset) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseFirewallCommittedRuleset)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.Annotations != nil {
		o.Annotations = *so.Annotations
	}
	if so.AssociatedTags != nil {
		o.AssociatedTags = *so.AssociatedTags
	}
	if so.CommittedTime != nil {
		o.CommittedTime = *so.CommittedTime
	}
	if so.CreateIdempotencyKey != nil {
		o.CreateIdempotencyKey = *so.CreateIdempotencyKey
	}
	if so.CreateTime != nil {
		o.CreateTime = *so.CreateTime
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.NormalizedTags != nil {
		o.NormalizedTags = *so.NormalizedTags
	}
	if so.ObjectID != nil {
		o.ObjectID = *so.ObjectID
	}
	if so.ObjectType != nil {
		o.ObjectType = *so.ObjectType
	}
	if so.Protected != nil {
		o.Protected = *so.Protected
	}
	if so.UpdateIdempotencyKey != nil {
		o.UpdateIdempotencyKey = *so.UpdateIdempotencyKey
	}
	if so.UpdateTime != nil {
		o.UpdateTime = *so.UpdateTime
	}
	if so.ZHash != nil {
		o.ZHash = *so.ZHash
	}
	if so.Zone != nil {
		o.Zone = *so.Zone
	}
}

// DeepCopy returns a deep copy if the FirewallCommittedRuleset.
func (o *FirewallCommittedRuleset) DeepCopy() *FirewallCommittedRuleset {

	if o == nil {
		return nil
	}

	out := &FirewallCommittedRuleset{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *FirewallCommittedRuleset.
func (o *FirewallCommittedRuleset) DeepCopyInto(out *FirewallCommittedRuleset) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy FirewallCommittedRuleset: %s", err))
	}

	*out = *target.(*FirewallCommittedRuleset)
}

// Validate valides the current information stored into the structure.
func (o *FirewallCommittedRuleset) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := ValidateTagsWithoutReservedPrefixes("associatedTags", o.AssociatedTags); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateStringInList("objectType", string(o.ObjectType), []string{"FirewallRuleset", "FirewallTemplate"}, false); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*FirewallCommittedRuleset) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := FirewallCommittedRulesetAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return FirewallCommittedRulesetLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*FirewallCommittedRuleset) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return FirewallCommittedRulesetAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *FirewallCommittedRuleset) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "annotations":
		return o.Annotations
	case "associatedTags":
		return o.AssociatedTags
	case "committedTime":
		return o.CommittedTime
	case "createIdempotencyKey":
		return o.CreateIdempotencyKey
	case "createTime":
		return o.CreateTime
	case "namespace":
		return o.Namespace
	case "normalizedTags":
		return o.NormalizedTags
	case "objectID":
		return o.ObjectID
	case "objectType":
		return o.ObjectType
	case "protected":
		return o.Protected
	case "updateIdempotencyKey":
		return o.UpdateIdempotencyKey
	case "updateTime":
		return o.UpdateTime
	case "zHash":
		return o.ZHash
	case "zone":
		return o.Zone
	}

	return nil
}

// FirewallCommittedRulesetAttributesMap represents the map of attribute for FirewallCommittedRuleset.
var FirewallCommittedRulesetAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `Identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"Annotations": {
		AllowedChoices: []string{},
		BSONFieldName:  "annotations",
		ConvertedName:  "Annotations",
		Description:    `Stores additional information about an entity.`,
		Exposed:        true,
		Getter:         true,
		Name:           "annotations",
		Setter:         true,
		Stored:         true,
		SubType:        "map[string][]string",
		Type:           "external",
	},
	"AssociatedTags": {
		AllowedChoices: []string{},
		BSONFieldName:  "associatedtags",
		ConvertedName:  "AssociatedTags",
		Description:    `List of tags attached to an entity.`,
		Exposed:        true,
		Getter:         true,
		Name:           "associatedTags",
		Setter:         true,
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"CommittedTime": {
		AllowedChoices: []string{},
		BSONFieldName:  "committedtime",
		ConvertedName:  "CommittedTime",
		Description:    `The date when the ruleset or template was committed.`,
		Exposed:        true,
		Name:           "committedTime",
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},

	"CreateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `Namespace tag attached to an entity.`,
		Exposed:        true,
		Filterable:     true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"NormalizedTags": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "normalizedtags",
		ConvertedName:  "NormalizedTags",
		Description:    `Contains the list of normalized tags of the entities.`,
		Exposed:        true,
		Getter:         true,
		Name:           "normalizedTags",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		SubType:        "string",
		Transient:      true,
		Type:           "list",
	},
	"ObjectID": {
		AllowedChoices: []string{},
		BSONFieldName:  "objectid",
		ConvertedName:  "ObjectID",
		Description:    `The ID of the ruleset or template that was committed.`,
		Exposed:        true,
		Name:           "objectID",
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"ObjectType": {
		AllowedChoices: []string{"FirewallRuleset", "FirewallTemplate"},
		BSONFieldName:  "objecttype",
		ConvertedName:  "ObjectType",
		DefaultValue:   FirewallCommittedRulesetObjectTypeFirewallRuleset,
		Description:    `The type of object committed.`,
		Exposed:        true,
		Name:           "objectType",
		Stored:         true,
		Type:           "enum",
	},
	"Protected": {
		AllowedChoices: []string{},
		BSONFieldName:  "protected",
		ConvertedName:  "Protected",
		Description:    `Defines if the object is protected.`,
		Exposed:        true,
		Getter:         true,
		Name:           "protected",
		Orderable:      true,
		Setter:         true,
		Stored:         true,
		Type:           "boolean",
	},

	"UpdateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
}

// FirewallCommittedRulesetLowerCaseAttributesMap represents the map of attribute for FirewallCommittedRuleset.
var FirewallCommittedRulesetLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `Identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"annotations": {
		AllowedChoices: []string{},
		BSONFieldName:  "annotations",
		ConvertedName:  "Annotations",
		Description:    `Stores additional information about an entity.`,
		Exposed:        true,
		Getter:         true,
		Name:           "annotations",
		Setter:         true,
		Stored:         true,
		SubType:        "map[string][]string",
		Type:           "external",
	},
	"associatedtags": {
		AllowedChoices: []string{},
		BSONFieldName:  "associatedtags",
		ConvertedName:  "AssociatedTags",
		Description:    `List of tags attached to an entity.`,
		Exposed:        true,
		Getter:         true,
		Name:           "associatedTags",
		Setter:         true,
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"committedtime": {
		AllowedChoices: []string{},
		BSONFieldName:  "committedtime",
		ConvertedName:  "CommittedTime",
		Description:    `The date when the ruleset or template was committed.`,
		Exposed:        true,
		Name:           "committedTime",
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},

	"createtime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `Namespace tag attached to an entity.`,
		Exposed:        true,
		Filterable:     true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"normalizedtags": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "normalizedtags",
		ConvertedName:  "NormalizedTags",
		Description:    `Contains the list of normalized tags of the entities.`,
		Exposed:        true,
		Getter:         true,
		Name:           "normalizedTags",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		SubType:        "string",
		Transient:      true,
		Type:           "list",
	},
	"objectid": {
		AllowedChoices: []string{},
		BSONFieldName:  "objectid",
		ConvertedName:  "ObjectID",
		Description:    `The ID of the ruleset or template that was committed.`,
		Exposed:        true,
		Name:           "objectID",
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"objecttype": {
		AllowedChoices: []string{"FirewallRuleset", "FirewallTemplate"},
		BSONFieldName:  "objecttype",
		ConvertedName:  "ObjectType",
		DefaultValue:   FirewallCommittedRulesetObjectTypeFirewallRuleset,
		Description:    `The type of object committed.`,
		Exposed:        true,
		Name:           "objectType",
		Stored:         true,
		Type:           "enum",
	},
	"protected": {
		AllowedChoices: []string{},
		BSONFieldName:  "protected",
		ConvertedName:  "Protected",
		Description:    `Defines if the object is protected.`,
		Exposed:        true,
		Getter:         true,
		Name:           "protected",
		Orderable:      true,
		Setter:         true,
		Stored:         true,
		Type:           "boolean",
	},

	"updatetime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
}

// SparseFirewallCommittedRulesetsList represents a list of SparseFirewallCommittedRulesets
type SparseFirewallCommittedRulesetsList []*SparseFirewallCommittedRuleset

// Identity returns the identity of the objects in the list.
func (o SparseFirewallCommittedRulesetsList) Identity() elemental.Identity {

	return FirewallCommittedRulesetIdentity
}

// Copy returns a pointer to a copy the SparseFirewallCommittedRulesetsList.
func (o SparseFirewallCommittedRulesetsList) Copy() elemental.Identifiables {

	copy := append(SparseFirewallCommittedRulesetsList{}, o...)
	return &copy
}

// Append appends the objects to the a new copy of the SparseFirewallCommittedRulesetsList.
func (o SparseFirewallCommittedRulesetsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(SparseFirewallCommittedRulesetsList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*SparseFirewallCommittedRuleset))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseFirewallCommittedRulesetsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseFirewallCommittedRulesetsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseFirewallCommittedRulesetsList converted to FirewallCommittedRulesetsList.
func (o SparseFirewallCommittedRulesetsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseFirewallCommittedRulesetsList) Version() int {

	return 1
}

// SparseFirewallCommittedRuleset represents the sparse version of a firewallcommittedruleset.
type SparseFirewallCommittedRuleset struct {
	// Identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Stores additional information about an entity.
	Annotations *map[string][]string `json:"annotations,omitempty" msgpack:"annotations,omitempty" bson:"annotations,omitempty" mapstructure:"annotations,omitempty"`

	// List of tags attached to an entity.
	AssociatedTags *[]string `json:"associatedTags,omitempty" msgpack:"associatedTags,omitempty" bson:"associatedtags,omitempty" mapstructure:"associatedTags,omitempty"`

	// The date when the ruleset or template was committed.
	CommittedTime *time.Time `json:"committedTime,omitempty" msgpack:"committedTime,omitempty" bson:"committedtime,omitempty" mapstructure:"committedTime,omitempty"`

	// internal idempotency key for a create operation.
	CreateIdempotencyKey *string `json:"-" msgpack:"-" bson:"createidempotencykey,omitempty" mapstructure:"-,omitempty"`

	// Creation date of the object.
	CreateTime *time.Time `json:"createTime,omitempty" msgpack:"createTime,omitempty" bson:"createtime,omitempty" mapstructure:"createTime,omitempty"`

	// Namespace tag attached to an entity.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Contains the list of normalized tags of the entities.
	NormalizedTags *[]string `json:"normalizedTags,omitempty" msgpack:"normalizedTags,omitempty" bson:"normalizedtags,omitempty" mapstructure:"normalizedTags,omitempty"`

	// The ID of the ruleset or template that was committed.
	ObjectID *time.Time `json:"objectID,omitempty" msgpack:"objectID,omitempty" bson:"objectid,omitempty" mapstructure:"objectID,omitempty"`

	// The type of object committed.
	ObjectType *FirewallCommittedRulesetObjectTypeValue `json:"objectType,omitempty" msgpack:"objectType,omitempty" bson:"objecttype,omitempty" mapstructure:"objectType,omitempty"`

	// Defines if the object is protected.
	Protected *bool `json:"protected,omitempty" msgpack:"protected,omitempty" bson:"protected,omitempty" mapstructure:"protected,omitempty"`

	// internal idempotency key for a update operation.
	UpdateIdempotencyKey *string `json:"-" msgpack:"-" bson:"updateidempotencykey,omitempty" mapstructure:"-,omitempty"`

	// Last update date of the object.
	UpdateTime *time.Time `json:"updateTime,omitempty" msgpack:"updateTime,omitempty" bson:"updatetime,omitempty" mapstructure:"updateTime,omitempty"`

	// geographical hash of the data. This is used for sharding and
	// georedundancy.
	ZHash *int `json:"-" msgpack:"-" bson:"zhash,omitempty" mapstructure:"-,omitempty"`

	// Logical storage zone. Used for sharding.
	Zone *int `json:"-" msgpack:"-" bson:"zone,omitempty" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseFirewallCommittedRuleset returns a new  SparseFirewallCommittedRuleset.
func NewSparseFirewallCommittedRuleset() *SparseFirewallCommittedRuleset {
	return &SparseFirewallCommittedRuleset{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseFirewallCommittedRuleset) Identity() elemental.Identity {

	return FirewallCommittedRulesetIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseFirewallCommittedRuleset) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseFirewallCommittedRuleset) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseFirewallCommittedRuleset) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseFirewallCommittedRuleset{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.Annotations != nil {
		s.Annotations = o.Annotations
	}
	if o.AssociatedTags != nil {
		s.AssociatedTags = o.AssociatedTags
	}
	if o.CommittedTime != nil {
		s.CommittedTime = o.CommittedTime
	}
	if o.CreateIdempotencyKey != nil {
		s.CreateIdempotencyKey = o.CreateIdempotencyKey
	}
	if o.CreateTime != nil {
		s.CreateTime = o.CreateTime
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.NormalizedTags != nil {
		s.NormalizedTags = o.NormalizedTags
	}
	if o.ObjectID != nil {
		s.ObjectID = o.ObjectID
	}
	if o.ObjectType != nil {
		s.ObjectType = o.ObjectType
	}
	if o.Protected != nil {
		s.Protected = o.Protected
	}
	if o.UpdateIdempotencyKey != nil {
		s.UpdateIdempotencyKey = o.UpdateIdempotencyKey
	}
	if o.UpdateTime != nil {
		s.UpdateTime = o.UpdateTime
	}
	if o.ZHash != nil {
		s.ZHash = o.ZHash
	}
	if o.Zone != nil {
		s.Zone = o.Zone
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseFirewallCommittedRuleset) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseFirewallCommittedRuleset{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.Annotations != nil {
		o.Annotations = s.Annotations
	}
	if s.AssociatedTags != nil {
		o.AssociatedTags = s.AssociatedTags
	}
	if s.CommittedTime != nil {
		o.CommittedTime = s.CommittedTime
	}
	if s.CreateIdempotencyKey != nil {
		o.CreateIdempotencyKey = s.CreateIdempotencyKey
	}
	if s.CreateTime != nil {
		o.CreateTime = s.CreateTime
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.NormalizedTags != nil {
		o.NormalizedTags = s.NormalizedTags
	}
	if s.ObjectID != nil {
		o.ObjectID = s.ObjectID
	}
	if s.ObjectType != nil {
		o.ObjectType = s.ObjectType
	}
	if s.Protected != nil {
		o.Protected = s.Protected
	}
	if s.UpdateIdempotencyKey != nil {
		o.UpdateIdempotencyKey = s.UpdateIdempotencyKey
	}
	if s.UpdateTime != nil {
		o.UpdateTime = s.UpdateTime
	}
	if s.ZHash != nil {
		o.ZHash = s.ZHash
	}
	if s.Zone != nil {
		o.Zone = s.Zone
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseFirewallCommittedRuleset) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseFirewallCommittedRuleset) ToPlain() elemental.PlainIdentifiable {

	out := NewFirewallCommittedRuleset()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.Annotations != nil {
		out.Annotations = *o.Annotations
	}
	if o.AssociatedTags != nil {
		out.AssociatedTags = *o.AssociatedTags
	}
	if o.CommittedTime != nil {
		out.CommittedTime = *o.CommittedTime
	}
	if o.CreateIdempotencyKey != nil {
		out.CreateIdempotencyKey = *o.CreateIdempotencyKey
	}
	if o.CreateTime != nil {
		out.CreateTime = *o.CreateTime
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.NormalizedTags != nil {
		out.NormalizedTags = *o.NormalizedTags
	}
	if o.ObjectID != nil {
		out.ObjectID = *o.ObjectID
	}
	if o.ObjectType != nil {
		out.ObjectType = *o.ObjectType
	}
	if o.Protected != nil {
		out.Protected = *o.Protected
	}
	if o.UpdateIdempotencyKey != nil {
		out.UpdateIdempotencyKey = *o.UpdateIdempotencyKey
	}
	if o.UpdateTime != nil {
		out.UpdateTime = *o.UpdateTime
	}
	if o.ZHash != nil {
		out.ZHash = *o.ZHash
	}
	if o.Zone != nil {
		out.Zone = *o.Zone
	}

	return out
}

// GetAnnotations returns the Annotations of the receiver.
func (o *SparseFirewallCommittedRuleset) GetAnnotations() (out map[string][]string) {

	if o.Annotations == nil {
		return
	}

	return *o.Annotations
}

// SetAnnotations sets the property Annotations of the receiver using the address of the given value.
func (o *SparseFirewallCommittedRuleset) SetAnnotations(annotations map[string][]string) {

	o.Annotations = &annotations
}

// GetAssociatedTags returns the AssociatedTags of the receiver.
func (o *SparseFirewallCommittedRuleset) GetAssociatedTags() (out []string) {

	if o.AssociatedTags == nil {
		return
	}

	return *o.AssociatedTags
}

// SetAssociatedTags sets the property AssociatedTags of the receiver using the address of the given value.
func (o *SparseFirewallCommittedRuleset) SetAssociatedTags(associatedTags []string) {

	o.AssociatedTags = &associatedTags
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *SparseFirewallCommittedRuleset) GetCreateTime() (out time.Time) {

	if o.CreateTime == nil {
		return
	}

	return *o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the address of the given value.
func (o *SparseFirewallCommittedRuleset) SetCreateTime(createTime time.Time) {

	o.CreateTime = &createTime
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseFirewallCommittedRuleset) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseFirewallCommittedRuleset) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// GetNormalizedTags returns the NormalizedTags of the receiver.
func (o *SparseFirewallCommittedRuleset) GetNormalizedTags() (out []string) {

	if o.NormalizedTags == nil {
		return
	}

	return *o.NormalizedTags
}

// SetNormalizedTags sets the property NormalizedTags of the receiver using the address of the given value.
func (o *SparseFirewallCommittedRuleset) SetNormalizedTags(normalizedTags []string) {

	o.NormalizedTags = &normalizedTags
}

// GetProtected returns the Protected of the receiver.
func (o *SparseFirewallCommittedRuleset) GetProtected() (out bool) {

	if o.Protected == nil {
		return
	}

	return *o.Protected
}

// SetProtected sets the property Protected of the receiver using the address of the given value.
func (o *SparseFirewallCommittedRuleset) SetProtected(protected bool) {

	o.Protected = &protected
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *SparseFirewallCommittedRuleset) GetUpdateTime() (out time.Time) {

	if o.UpdateTime == nil {
		return
	}

	return *o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the address of the given value.
func (o *SparseFirewallCommittedRuleset) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = &updateTime
}

// DeepCopy returns a deep copy if the SparseFirewallCommittedRuleset.
func (o *SparseFirewallCommittedRuleset) DeepCopy() *SparseFirewallCommittedRuleset {

	if o == nil {
		return nil
	}

	out := &SparseFirewallCommittedRuleset{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseFirewallCommittedRuleset.
func (o *SparseFirewallCommittedRuleset) DeepCopyInto(out *SparseFirewallCommittedRuleset) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseFirewallCommittedRuleset: %s", err))
	}

	*out = *target.(*SparseFirewallCommittedRuleset)
}

type mongoAttributesFirewallCommittedRuleset struct {
	ID                   bson.ObjectId                           `bson:"_id,omitempty"`
	Annotations          map[string][]string                     `bson:"annotations"`
	AssociatedTags       []string                                `bson:"associatedtags"`
	CommittedTime        time.Time                               `bson:"committedtime"`
	CreateIdempotencyKey string                                  `bson:"createidempotencykey"`
	CreateTime           time.Time                               `bson:"createtime"`
	Namespace            string                                  `bson:"namespace"`
	NormalizedTags       []string                                `bson:"normalizedtags"`
	ObjectID             time.Time                               `bson:"objectid"`
	ObjectType           FirewallCommittedRulesetObjectTypeValue `bson:"objecttype"`
	Protected            bool                                    `bson:"protected"`
	UpdateIdempotencyKey string                                  `bson:"updateidempotencykey"`
	UpdateTime           time.Time                               `bson:"updatetime"`
	ZHash                int                                     `bson:"zhash"`
	Zone                 int                                     `bson:"zone"`
}
type mongoAttributesSparseFirewallCommittedRuleset struct {
	ID                   bson.ObjectId                            `bson:"_id,omitempty"`
	Annotations          *map[string][]string                     `bson:"annotations,omitempty"`
	AssociatedTags       *[]string                                `bson:"associatedtags,omitempty"`
	CommittedTime        *time.Time                               `bson:"committedtime,omitempty"`
	CreateIdempotencyKey *string                                  `bson:"createidempotencykey,omitempty"`
	CreateTime           *time.Time                               `bson:"createtime,omitempty"`
	Namespace            *string                                  `bson:"namespace,omitempty"`
	NormalizedTags       *[]string                                `bson:"normalizedtags,omitempty"`
	ObjectID             *time.Time                               `bson:"objectid,omitempty"`
	ObjectType           *FirewallCommittedRulesetObjectTypeValue `bson:"objecttype,omitempty"`
	Protected            *bool                                    `bson:"protected,omitempty"`
	UpdateIdempotencyKey *string                                  `bson:"updateidempotencykey,omitempty"`
	UpdateTime           *time.Time                               `bson:"updatetime,omitempty"`
	ZHash                *int                                     `bson:"zhash,omitempty"`
	Zone                 *int                                     `bson:"zone,omitempty"`
}
