// Code generated by elegen. DO NOT EDIT.
// Source: go.aporeto.io/elemental (templates/identities_registry.gotpl)

package api

import "go.aporeto.io/elemental"

var (
	identityNamesMap = map[string]elemental.Identity{

		"awsfirewall":      AWSFirewallIdentity,
		"awslogdefinition": AWSLogDefinitionIdentity,

		"deploymentadvisorsubnethelper": DeploymentAdvisorSubnetHelperIdentity,
		"deploymentadvisorterraform":    DeploymentAdvisorTerraformIdentity,
		"firewallappidlist":             FirewallAppIDListIdentity,

		"firewallapplicationgroup": FirewallApplicationGroupIdentity,

		"firewallcertificate":      FirewallCertificateIdentity,
		"firewallcidrlist":         FirewallCIDRlistIdentity,
		"firewallcommitaction":     FirewallCommitActionIdentity,
		"firewallcommittedruleset": FirewallCommittedRulesetIdentity,

		"firewallcountrycodelist":    FirewallCountryCodelistIdentity,
		"firewallcustomexternalfeed": FirewallCustomExternalFeedIdentity,
		"firewallcustomurlcategory":  FirewallCustomURLCategoryIdentity,

		"firewallexternalfeedlist": FirewallExternalFeedListIdentity,
		"firewallfqdnlist":         FirewallFQDNListIdentity,
		"firewallgroup":            FirewallGroupIdentity,
		"firewalllicensingcredits": FirewallLicensingCreditsIdentity,

		"firewallrollbackaction":  FirewallRollbackActionIdentity,
		"firewallrule":            FirewallRuleIdentity,
		"firewallruleset":         FirewallRulesetIdentity,
		"firewallsecurityprofile": FirewallSecurityProfileIdentity,

		"firewalltemplate": FirewallTemplateIdentity,

		"firewallurlcategorylist": FirewallURLCategoryListIdentity,

		"logquery": LogQueryIdentity,

		"pcfwaccount": PCFWAccountIdentity,
		"pcfwtenant":  PCFWTenantIdentity,
		"root":        RootIdentity,

		"topquery": TopQueryIdentity,

		"totalquery": TotalQueryIdentity,
		"trendquery": TrendQueryIdentity,
	}

	identitycategoriesMap = map[string]elemental.Identity{

		"awsfirewalls":      AWSFirewallIdentity,
		"awslogdefinitions": AWSLogDefinitionIdentity,

		"deploymentadvisorsubnethelpers": DeploymentAdvisorSubnetHelperIdentity,
		"deploymentadvisorterraforms":    DeploymentAdvisorTerraformIdentity,
		"firewallappidlist":              FirewallAppIDListIdentity,

		"firewallapplicationgroups": FirewallApplicationGroupIdentity,

		"firewallcertificates":      FirewallCertificateIdentity,
		"firewallcidrlists":         FirewallCIDRlistIdentity,
		"firewallcommitactions":     FirewallCommitActionIdentity,
		"firewallcommittedrulesets": FirewallCommittedRulesetIdentity,

		"firewallcountrycodelist":     FirewallCountryCodelistIdentity,
		"firewallcustomexternalfeeds": FirewallCustomExternalFeedIdentity,
		"firewallcustomurlcategories": FirewallCustomURLCategoryIdentity,

		"firewallexternalfeedlists": FirewallExternalFeedListIdentity,
		"firewallfqdnlists":         FirewallFQDNListIdentity,
		"firewallgroups":            FirewallGroupIdentity,
		"firewalllicensingcredits":  FirewallLicensingCreditsIdentity,

		"firewallrollbackactions":  FirewallRollbackActionIdentity,
		"firewallrules":            FirewallRuleIdentity,
		"firewallrulesets":         FirewallRulesetIdentity,
		"firewallsecurityprofiles": FirewallSecurityProfileIdentity,

		"firewalltemplates": FirewallTemplateIdentity,

		"firewallurlcategorylists": FirewallURLCategoryListIdentity,

		"logqueries": LogQueryIdentity,

		"pcfwaccounts": PCFWAccountIdentity,
		"pcfwtenants":  PCFWTenantIdentity,
		"root":         RootIdentity,

		"topqueries": TopQueryIdentity,

		"totalqueries": TotalQueryIdentity,
		"trendqueries": TrendQueryIdentity,
	}

	aliasesMap = map[string]elemental.Identity{}

	indexesMap = map[string][][]string{
		"awsfirewall": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"awslogdefinition": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"deploymentadvisorsubnethelper": nil,
		"deploymentadvisorterraform": {
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallappidlist": {
			{"namespace"},
		},
		"firewallapplicationgroup": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallcertificate": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallcidrlist": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallcommitaction": nil,
		"firewallcommittedruleset": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
		},
		"firewallcountrycodelist": {
			{"namespace"},
		},
		"firewallcustomexternalfeed": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallcustomurlcategory": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallexternalfeedlist": {
			{"namespace"},
		},
		"firewallfqdnlist": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallgroup": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewalllicensingcredits": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "firewallResource"},
		},
		"firewallrollbackaction": nil,
		"firewallrule": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
		},
		"firewallruleset": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallsecurityprofile": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewalltemplate": {
			{":shard", ":unique", "zone", "zHash"},
			{"name"},
			{"namespace"},
			{"namespace", "name"},
		},
		"firewallurlcategorylist": {
			{"namespace"},
		},
		"logquery": nil,
		"pcfwaccount": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
		},
		"pcfwtenant": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
		},
		"root":       nil,
		"topquery":   nil,
		"totalquery": nil,
		"trendquery": nil,
	}
)

// ModelVersion returns the current version of the model.
func ModelVersion() float64 { return 1 }

type modelManager struct{}

func (f modelManager) IdentityFromName(name string) elemental.Identity {

	return identityNamesMap[name]
}

func (f modelManager) IdentityFromCategory(category string) elemental.Identity {

	return identitycategoriesMap[category]
}

func (f modelManager) IdentityFromAlias(alias string) elemental.Identity {

	return aliasesMap[alias]
}

func (f modelManager) IdentityFromAny(any string) (i elemental.Identity) {

	if i = f.IdentityFromName(any); !i.IsEmpty() {
		return i
	}

	if i = f.IdentityFromCategory(any); !i.IsEmpty() {
		return i
	}

	return f.IdentityFromAlias(any)
}

func (f modelManager) Identifiable(identity elemental.Identity) elemental.Identifiable {

	switch identity {

	case AWSFirewallIdentity:
		return NewAWSFirewall()
	case AWSLogDefinitionIdentity:
		return NewAWSLogDefinition()
	case DeploymentAdvisorSubnetHelperIdentity:
		return NewDeploymentAdvisorSubnetHelper()
	case DeploymentAdvisorTerraformIdentity:
		return NewDeploymentAdvisorTerraform()
	case FirewallAppIDListIdentity:
		return NewFirewallAppIDList()
	case FirewallApplicationGroupIdentity:
		return NewFirewallApplicationGroup()
	case FirewallCertificateIdentity:
		return NewFirewallCertificate()
	case FirewallCIDRlistIdentity:
		return NewFirewallCIDRlist()
	case FirewallCommitActionIdentity:
		return NewFirewallCommitAction()
	case FirewallCommittedRulesetIdentity:
		return NewFirewallCommittedRuleset()
	case FirewallCountryCodelistIdentity:
		return NewFirewallCountryCodelist()
	case FirewallCustomExternalFeedIdentity:
		return NewFirewallCustomExternalFeed()
	case FirewallCustomURLCategoryIdentity:
		return NewFirewallCustomURLCategory()
	case FirewallExternalFeedListIdentity:
		return NewFirewallExternalFeedList()
	case FirewallFQDNListIdentity:
		return NewFirewallFQDNList()
	case FirewallGroupIdentity:
		return NewFirewallGroup()
	case FirewallLicensingCreditsIdentity:
		return NewFirewallLicensingCredits()
	case FirewallRollbackActionIdentity:
		return NewFirewallRollbackAction()
	case FirewallRuleIdentity:
		return NewFirewallRule()
	case FirewallRulesetIdentity:
		return NewFirewallRuleset()
	case FirewallSecurityProfileIdentity:
		return NewFirewallSecurityProfile()
	case FirewallTemplateIdentity:
		return NewFirewallTemplate()
	case FirewallURLCategoryListIdentity:
		return NewFirewallURLCategoryList()
	case LogQueryIdentity:
		return NewLogQuery()
	case PCFWAccountIdentity:
		return NewPCFWAccount()
	case PCFWTenantIdentity:
		return NewPCFWTenant()
	case RootIdentity:
		return NewRoot()
	case TopQueryIdentity:
		return NewTopQuery()
	case TotalQueryIdentity:
		return NewTotalQuery()
	case TrendQueryIdentity:
		return NewTrendQuery()
	default:
		return nil
	}
}

func (f modelManager) SparseIdentifiable(identity elemental.Identity) elemental.SparseIdentifiable {

	switch identity {

	case AWSFirewallIdentity:
		return NewSparseAWSFirewall()
	case AWSLogDefinitionIdentity:
		return NewSparseAWSLogDefinition()
	case DeploymentAdvisorSubnetHelperIdentity:
		return NewSparseDeploymentAdvisorSubnetHelper()
	case DeploymentAdvisorTerraformIdentity:
		return NewSparseDeploymentAdvisorTerraform()
	case FirewallAppIDListIdentity:
		return NewSparseFirewallAppIDList()
	case FirewallApplicationGroupIdentity:
		return NewSparseFirewallApplicationGroup()
	case FirewallCertificateIdentity:
		return NewSparseFirewallCertificate()
	case FirewallCIDRlistIdentity:
		return NewSparseFirewallCIDRlist()
	case FirewallCommitActionIdentity:
		return NewSparseFirewallCommitAction()
	case FirewallCommittedRulesetIdentity:
		return NewSparseFirewallCommittedRuleset()
	case FirewallCountryCodelistIdentity:
		return NewSparseFirewallCountryCodelist()
	case FirewallCustomExternalFeedIdentity:
		return NewSparseFirewallCustomExternalFeed()
	case FirewallCustomURLCategoryIdentity:
		return NewSparseFirewallCustomURLCategory()
	case FirewallExternalFeedListIdentity:
		return NewSparseFirewallExternalFeedList()
	case FirewallFQDNListIdentity:
		return NewSparseFirewallFQDNList()
	case FirewallGroupIdentity:
		return NewSparseFirewallGroup()
	case FirewallLicensingCreditsIdentity:
		return NewSparseFirewallLicensingCredits()
	case FirewallRollbackActionIdentity:
		return NewSparseFirewallRollbackAction()
	case FirewallRuleIdentity:
		return NewSparseFirewallRule()
	case FirewallRulesetIdentity:
		return NewSparseFirewallRuleset()
	case FirewallSecurityProfileIdentity:
		return NewSparseFirewallSecurityProfile()
	case FirewallTemplateIdentity:
		return NewSparseFirewallTemplate()
	case FirewallURLCategoryListIdentity:
		return NewSparseFirewallURLCategoryList()
	case LogQueryIdentity:
		return NewSparseLogQuery()
	case PCFWAccountIdentity:
		return NewSparsePCFWAccount()
	case PCFWTenantIdentity:
		return NewSparsePCFWTenant()
	case TopQueryIdentity:
		return NewSparseTopQuery()
	case TotalQueryIdentity:
		return NewSparseTotalQuery()
	case TrendQueryIdentity:
		return NewSparseTrendQuery()
	default:
		return nil
	}
}

func (f modelManager) Indexes(identity elemental.Identity) [][]string {

	return indexesMap[identity.Name]
}

func (f modelManager) IdentifiableFromString(any string) elemental.Identifiable {

	return f.Identifiable(f.IdentityFromAny(any))
}

func (f modelManager) Identifiables(identity elemental.Identity) elemental.Identifiables {

	switch identity {

	case AWSFirewallIdentity:
		return &AWSFirewallsList{}
	case AWSLogDefinitionIdentity:
		return &AWSLogDefinitionsList{}
	case DeploymentAdvisorSubnetHelperIdentity:
		return &DeploymentAdvisorSubnetHelpersList{}
	case DeploymentAdvisorTerraformIdentity:
		return &DeploymentAdvisorTerraformsList{}
	case FirewallAppIDListIdentity:
		return &FirewallAppIDListsList{}
	case FirewallApplicationGroupIdentity:
		return &FirewallApplicationGroupsList{}
	case FirewallCertificateIdentity:
		return &FirewallCertificatesList{}
	case FirewallCIDRlistIdentity:
		return &FirewallCIDRlistsList{}
	case FirewallCommitActionIdentity:
		return &FirewallCommitActionsList{}
	case FirewallCommittedRulesetIdentity:
		return &FirewallCommittedRulesetsList{}
	case FirewallCountryCodelistIdentity:
		return &FirewallCountryCodelistsList{}
	case FirewallCustomExternalFeedIdentity:
		return &FirewallCustomExternalFeedsList{}
	case FirewallCustomURLCategoryIdentity:
		return &FirewallCustomURLCategoriesList{}
	case FirewallExternalFeedListIdentity:
		return &FirewallExternalFeedListsList{}
	case FirewallFQDNListIdentity:
		return &FirewallFQDNListsList{}
	case FirewallGroupIdentity:
		return &FirewallGroupsList{}
	case FirewallLicensingCreditsIdentity:
		return &FirewallLicensingCreditsList{}
	case FirewallRollbackActionIdentity:
		return &FirewallRollbackActionsList{}
	case FirewallRuleIdentity:
		return &FirewallRulesList{}
	case FirewallRulesetIdentity:
		return &FirewallRulesetsList{}
	case FirewallSecurityProfileIdentity:
		return &FirewallSecurityProfilesList{}
	case FirewallTemplateIdentity:
		return &FirewallTemplatesList{}
	case FirewallURLCategoryListIdentity:
		return &FirewallURLCategoryListsList{}
	case LogQueryIdentity:
		return &LogQueriesList{}
	case PCFWAccountIdentity:
		return &PCFWAccountsList{}
	case PCFWTenantIdentity:
		return &PCFWTenantsList{}
	case TopQueryIdentity:
		return &TopQueriesList{}
	case TotalQueryIdentity:
		return &TotalQueriesList{}
	case TrendQueryIdentity:
		return &TrendQueriesList{}
	default:
		return nil
	}
}

func (f modelManager) SparseIdentifiables(identity elemental.Identity) elemental.SparseIdentifiables {

	switch identity {

	case AWSFirewallIdentity:
		return &SparseAWSFirewallsList{}
	case AWSLogDefinitionIdentity:
		return &SparseAWSLogDefinitionsList{}
	case DeploymentAdvisorSubnetHelperIdentity:
		return &SparseDeploymentAdvisorSubnetHelpersList{}
	case DeploymentAdvisorTerraformIdentity:
		return &SparseDeploymentAdvisorTerraformsList{}
	case FirewallAppIDListIdentity:
		return &SparseFirewallAppIDListsList{}
	case FirewallApplicationGroupIdentity:
		return &SparseFirewallApplicationGroupsList{}
	case FirewallCertificateIdentity:
		return &SparseFirewallCertificatesList{}
	case FirewallCIDRlistIdentity:
		return &SparseFirewallCIDRlistsList{}
	case FirewallCommitActionIdentity:
		return &SparseFirewallCommitActionsList{}
	case FirewallCommittedRulesetIdentity:
		return &SparseFirewallCommittedRulesetsList{}
	case FirewallCountryCodelistIdentity:
		return &SparseFirewallCountryCodelistsList{}
	case FirewallCustomExternalFeedIdentity:
		return &SparseFirewallCustomExternalFeedsList{}
	case FirewallCustomURLCategoryIdentity:
		return &SparseFirewallCustomURLCategoriesList{}
	case FirewallExternalFeedListIdentity:
		return &SparseFirewallExternalFeedListsList{}
	case FirewallFQDNListIdentity:
		return &SparseFirewallFQDNListsList{}
	case FirewallGroupIdentity:
		return &SparseFirewallGroupsList{}
	case FirewallLicensingCreditsIdentity:
		return &SparseFirewallLicensingCreditsList{}
	case FirewallRollbackActionIdentity:
		return &SparseFirewallRollbackActionsList{}
	case FirewallRuleIdentity:
		return &SparseFirewallRulesList{}
	case FirewallRulesetIdentity:
		return &SparseFirewallRulesetsList{}
	case FirewallSecurityProfileIdentity:
		return &SparseFirewallSecurityProfilesList{}
	case FirewallTemplateIdentity:
		return &SparseFirewallTemplatesList{}
	case FirewallURLCategoryListIdentity:
		return &SparseFirewallURLCategoryListsList{}
	case LogQueryIdentity:
		return &SparseLogQueriesList{}
	case PCFWAccountIdentity:
		return &SparsePCFWAccountsList{}
	case PCFWTenantIdentity:
		return &SparsePCFWTenantsList{}
	case TopQueryIdentity:
		return &SparseTopQueriesList{}
	case TotalQueryIdentity:
		return &SparseTotalQueriesList{}
	case TrendQueryIdentity:
		return &SparseTrendQueriesList{}
	default:
		return nil
	}
}

func (f modelManager) IdentifiablesFromString(any string) elemental.Identifiables {

	return f.Identifiables(f.IdentityFromAny(any))
}

func (f modelManager) Relationships() elemental.RelationshipsRegistry {

	return relationshipsRegistry
}

func (f modelManager) AllIdentities() []elemental.Identity {
	return AllIdentities()
}

var manager = modelManager{}

// Manager returns the model elemental.ModelManager.
func Manager() elemental.ModelManager { return manager }

// AllIdentities returns all existing identities.
func AllIdentities() []elemental.Identity {

	return []elemental.Identity{
		AWSFirewallIdentity,
		AWSLogDefinitionIdentity,
		DeploymentAdvisorSubnetHelperIdentity,
		DeploymentAdvisorTerraformIdentity,
		FirewallAppIDListIdentity,
		FirewallApplicationGroupIdentity,
		FirewallCertificateIdentity,
		FirewallCIDRlistIdentity,
		FirewallCommitActionIdentity,
		FirewallCommittedRulesetIdentity,
		FirewallCountryCodelistIdentity,
		FirewallCustomExternalFeedIdentity,
		FirewallCustomURLCategoryIdentity,
		FirewallExternalFeedListIdentity,
		FirewallFQDNListIdentity,
		FirewallGroupIdentity,
		FirewallLicensingCreditsIdentity,
		FirewallRollbackActionIdentity,
		FirewallRuleIdentity,
		FirewallRulesetIdentity,
		FirewallSecurityProfileIdentity,
		FirewallTemplateIdentity,
		FirewallURLCategoryListIdentity,
		LogQueryIdentity,
		PCFWAccountIdentity,
		PCFWTenantIdentity,
		RootIdentity,
		TopQueryIdentity,
		TotalQueryIdentity,
		TrendQueryIdentity,
	}
}

// AliasesForIdentity returns all the aliases for the given identity.
func AliasesForIdentity(identity elemental.Identity) []string {

	switch identity {
	case AWSFirewallIdentity:
		return []string{}
	case AWSLogDefinitionIdentity:
		return []string{}
	case DeploymentAdvisorSubnetHelperIdentity:
		return []string{}
	case DeploymentAdvisorTerraformIdentity:
		return []string{}
	case FirewallAppIDListIdentity:
		return []string{}
	case FirewallApplicationGroupIdentity:
		return []string{}
	case FirewallCertificateIdentity:
		return []string{}
	case FirewallCIDRlistIdentity:
		return []string{}
	case FirewallCommitActionIdentity:
		return []string{}
	case FirewallCommittedRulesetIdentity:
		return []string{}
	case FirewallCountryCodelistIdentity:
		return []string{}
	case FirewallCustomExternalFeedIdentity:
		return []string{}
	case FirewallCustomURLCategoryIdentity:
		return []string{}
	case FirewallExternalFeedListIdentity:
		return []string{}
	case FirewallFQDNListIdentity:
		return []string{}
	case FirewallGroupIdentity:
		return []string{}
	case FirewallLicensingCreditsIdentity:
		return []string{}
	case FirewallRollbackActionIdentity:
		return []string{}
	case FirewallRuleIdentity:
		return []string{}
	case FirewallRulesetIdentity:
		return []string{}
	case FirewallSecurityProfileIdentity:
		return []string{}
	case FirewallTemplateIdentity:
		return []string{}
	case FirewallURLCategoryListIdentity:
		return []string{}
	case LogQueryIdentity:
		return []string{}
	case PCFWAccountIdentity:
		return []string{}
	case PCFWTenantIdentity:
		return []string{}
	case RootIdentity:
		return []string{}
	case TopQueryIdentity:
		return []string{}
	case TotalQueryIdentity:
		return []string{}
	case TrendQueryIdentity:
		return []string{}
	}

	return nil
}
