// Code generated by elegen. DO NOT EDIT.
// Source: go.aporeto.io/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.aporeto.io/elemental"
)

// PCFWAccountMirrorTerraformIdentity represents the Identity of the object.
var PCFWAccountMirrorTerraformIdentity = elemental.Identity{
	Name:     "pcfwaccountmirrorterraform",
	Category: "pcfwaccountmirrorterraform",
	Package:  "deploymentadvisor",
	Private:  false,
}

// PCFWAccountMirrorTerraformsList represents a list of PCFWAccountMirrorTerraforms
type PCFWAccountMirrorTerraformsList []*PCFWAccountMirrorTerraform

// Identity returns the identity of the objects in the list.
func (o PCFWAccountMirrorTerraformsList) Identity() elemental.Identity {

	return PCFWAccountMirrorTerraformIdentity
}

// Copy returns a pointer to a copy the PCFWAccountMirrorTerraformsList.
func (o PCFWAccountMirrorTerraformsList) Copy() elemental.Identifiables {

	copy := append(PCFWAccountMirrorTerraformsList{}, o...)
	return &copy
}

// Append appends the objects to the a new copy of the PCFWAccountMirrorTerraformsList.
func (o PCFWAccountMirrorTerraformsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(PCFWAccountMirrorTerraformsList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*PCFWAccountMirrorTerraform))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o PCFWAccountMirrorTerraformsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o PCFWAccountMirrorTerraformsList) DefaultOrder() []string {

	return []string{
		"name",
	}
}

// ToSparse returns the PCFWAccountMirrorTerraformsList converted to SparsePCFWAccountMirrorTerraformsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o PCFWAccountMirrorTerraformsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparsePCFWAccountMirrorTerraformsList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToSparse(fields...).(*SparsePCFWAccountMirrorTerraform)
	}

	return out
}

// Version returns the version of the content.
func (o PCFWAccountMirrorTerraformsList) Version() int {

	return 1
}

// PCFWAccountMirrorTerraform represents the model of a pcfwaccountmirrorterraform
type PCFWAccountMirrorTerraform struct {
	// Identifier of the object.
	ID string `json:"ID" msgpack:"ID" bson:"-" mapstructure:"ID,omitempty"`

	// Description of the object.
	Description string `json:"description" msgpack:"description" bson:"description" mapstructure:"description,omitempty"`

	// Name of the entity.
	Name string `json:"name" msgpack:"name" bson:"name" mapstructure:"name,omitempty"`

	// Namespace tag attached to an entity.
	Namespace string `json:"namespace" msgpack:"namespace" bson:"namespace" mapstructure:"namespace,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewPCFWAccountMirrorTerraform returns a new *PCFWAccountMirrorTerraform
func NewPCFWAccountMirrorTerraform() *PCFWAccountMirrorTerraform {

	return &PCFWAccountMirrorTerraform{
		ModelVersion: 1,
	}
}

// Identity returns the Identity of the object.
func (o *PCFWAccountMirrorTerraform) Identity() elemental.Identity {

	return PCFWAccountMirrorTerraformIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *PCFWAccountMirrorTerraform) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *PCFWAccountMirrorTerraform) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *PCFWAccountMirrorTerraform) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesPCFWAccountMirrorTerraform{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.Description = o.Description
	s.Name = o.Name
	s.Namespace = o.Namespace

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *PCFWAccountMirrorTerraform) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesPCFWAccountMirrorTerraform{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.Description = s.Description
	o.Name = s.Name
	o.Namespace = s.Namespace

	return nil
}

// Version returns the hardcoded version of the model.
func (o *PCFWAccountMirrorTerraform) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *PCFWAccountMirrorTerraform) BleveType() string {

	return "pcfwaccountmirrorterraform"
}

// DefaultOrder returns the list of default ordering fields.
func (o *PCFWAccountMirrorTerraform) DefaultOrder() []string {

	return []string{
		"name",
	}
}

// Doc returns the documentation for the object
func (o *PCFWAccountMirrorTerraform) Doc() string {

	return `Represents PCFW account terraform generator.`
}

func (o *PCFWAccountMirrorTerraform) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetDescription returns the Description of the receiver.
func (o *PCFWAccountMirrorTerraform) GetDescription() string {

	return o.Description
}

// SetDescription sets the property Description of the receiver using the given value.
func (o *PCFWAccountMirrorTerraform) SetDescription(description string) {

	o.Description = description
}

// GetName returns the Name of the receiver.
func (o *PCFWAccountMirrorTerraform) GetName() string {

	return o.Name
}

// SetName sets the property Name of the receiver using the given value.
func (o *PCFWAccountMirrorTerraform) SetName(name string) {

	o.Name = name
}

// GetNamespace returns the Namespace of the receiver.
func (o *PCFWAccountMirrorTerraform) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *PCFWAccountMirrorTerraform) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *PCFWAccountMirrorTerraform) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparsePCFWAccountMirrorTerraform{
			ID:          &o.ID,
			Description: &o.Description,
			Name:        &o.Name,
			Namespace:   &o.Namespace,
		}
	}

	sp := &SparsePCFWAccountMirrorTerraform{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "description":
			sp.Description = &(o.Description)
		case "name":
			sp.Name = &(o.Name)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparsePCFWAccountMirrorTerraform to the object.
func (o *PCFWAccountMirrorTerraform) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparsePCFWAccountMirrorTerraform)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.Description != nil {
		o.Description = *so.Description
	}
	if so.Name != nil {
		o.Name = *so.Name
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
}

// DeepCopy returns a deep copy if the PCFWAccountMirrorTerraform.
func (o *PCFWAccountMirrorTerraform) DeepCopy() *PCFWAccountMirrorTerraform {

	if o == nil {
		return nil
	}

	out := &PCFWAccountMirrorTerraform{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *PCFWAccountMirrorTerraform.
func (o *PCFWAccountMirrorTerraform) DeepCopyInto(out *PCFWAccountMirrorTerraform) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy PCFWAccountMirrorTerraform: %s", err))
	}

	*out = *target.(*PCFWAccountMirrorTerraform)
}

// Validate valides the current information stored into the structure.
func (o *PCFWAccountMirrorTerraform) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateMaximumLength("description", o.Description, 1024, false); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateMaximumLength("name", o.Name, 256, false); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*PCFWAccountMirrorTerraform) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := PCFWAccountMirrorTerraformAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return PCFWAccountMirrorTerraformLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*PCFWAccountMirrorTerraform) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return PCFWAccountMirrorTerraformAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *PCFWAccountMirrorTerraform) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "description":
		return o.Description
	case "name":
		return o.Name
	case "namespace":
		return o.Namespace
	}

	return nil
}

// PCFWAccountMirrorTerraformAttributesMap represents the map of attribute for PCFWAccountMirrorTerraform.
var PCFWAccountMirrorTerraformAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `Identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"Description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `Description of the object.`,
		Exposed:        true,
		Getter:         true,
		MaxLength:      1024,
		Name:           "description",
		Orderable:      true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"Name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `Name of the entity.`,
		Exposed:        true,
		Filterable:     true,
		Getter:         true,
		MaxLength:      256,
		Name:           "name",
		Orderable:      true,
		Required:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `Namespace tag attached to an entity.`,
		Exposed:        true,
		Filterable:     true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
}

// PCFWAccountMirrorTerraformLowerCaseAttributesMap represents the map of attribute for PCFWAccountMirrorTerraform.
var PCFWAccountMirrorTerraformLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `Identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `Description of the object.`,
		Exposed:        true,
		Getter:         true,
		MaxLength:      1024,
		Name:           "description",
		Orderable:      true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `Name of the entity.`,
		Exposed:        true,
		Filterable:     true,
		Getter:         true,
		MaxLength:      256,
		Name:           "name",
		Orderable:      true,
		Required:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `Namespace tag attached to an entity.`,
		Exposed:        true,
		Filterable:     true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
}

// SparsePCFWAccountMirrorTerraformsList represents a list of SparsePCFWAccountMirrorTerraforms
type SparsePCFWAccountMirrorTerraformsList []*SparsePCFWAccountMirrorTerraform

// Identity returns the identity of the objects in the list.
func (o SparsePCFWAccountMirrorTerraformsList) Identity() elemental.Identity {

	return PCFWAccountMirrorTerraformIdentity
}

// Copy returns a pointer to a copy the SparsePCFWAccountMirrorTerraformsList.
func (o SparsePCFWAccountMirrorTerraformsList) Copy() elemental.Identifiables {

	copy := append(SparsePCFWAccountMirrorTerraformsList{}, o...)
	return &copy
}

// Append appends the objects to the a new copy of the SparsePCFWAccountMirrorTerraformsList.
func (o SparsePCFWAccountMirrorTerraformsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(SparsePCFWAccountMirrorTerraformsList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*SparsePCFWAccountMirrorTerraform))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparsePCFWAccountMirrorTerraformsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparsePCFWAccountMirrorTerraformsList) DefaultOrder() []string {

	return []string{
		"name",
	}
}

// ToPlain returns the SparsePCFWAccountMirrorTerraformsList converted to PCFWAccountMirrorTerraformsList.
func (o SparsePCFWAccountMirrorTerraformsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparsePCFWAccountMirrorTerraformsList) Version() int {

	return 1
}

// SparsePCFWAccountMirrorTerraform represents the sparse version of a pcfwaccountmirrorterraform.
type SparsePCFWAccountMirrorTerraform struct {
	// Identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Description of the object.
	Description *string `json:"description,omitempty" msgpack:"description,omitempty" bson:"description,omitempty" mapstructure:"description,omitempty"`

	// Name of the entity.
	Name *string `json:"name,omitempty" msgpack:"name,omitempty" bson:"name,omitempty" mapstructure:"name,omitempty"`

	// Namespace tag attached to an entity.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparsePCFWAccountMirrorTerraform returns a new  SparsePCFWAccountMirrorTerraform.
func NewSparsePCFWAccountMirrorTerraform() *SparsePCFWAccountMirrorTerraform {
	return &SparsePCFWAccountMirrorTerraform{}
}

// Identity returns the Identity of the sparse object.
func (o *SparsePCFWAccountMirrorTerraform) Identity() elemental.Identity {

	return PCFWAccountMirrorTerraformIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparsePCFWAccountMirrorTerraform) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparsePCFWAccountMirrorTerraform) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparsePCFWAccountMirrorTerraform) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparsePCFWAccountMirrorTerraform{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.Description != nil {
		s.Description = o.Description
	}
	if o.Name != nil {
		s.Name = o.Name
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparsePCFWAccountMirrorTerraform) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparsePCFWAccountMirrorTerraform{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.Description != nil {
		o.Description = s.Description
	}
	if s.Name != nil {
		o.Name = s.Name
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparsePCFWAccountMirrorTerraform) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparsePCFWAccountMirrorTerraform) ToPlain() elemental.PlainIdentifiable {

	out := NewPCFWAccountMirrorTerraform()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.Description != nil {
		out.Description = *o.Description
	}
	if o.Name != nil {
		out.Name = *o.Name
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}

	return out
}

// GetDescription returns the Description of the receiver.
func (o *SparsePCFWAccountMirrorTerraform) GetDescription() (out string) {

	if o.Description == nil {
		return
	}

	return *o.Description
}

// SetDescription sets the property Description of the receiver using the address of the given value.
func (o *SparsePCFWAccountMirrorTerraform) SetDescription(description string) {

	o.Description = &description
}

// GetName returns the Name of the receiver.
func (o *SparsePCFWAccountMirrorTerraform) GetName() (out string) {

	if o.Name == nil {
		return
	}

	return *o.Name
}

// SetName sets the property Name of the receiver using the address of the given value.
func (o *SparsePCFWAccountMirrorTerraform) SetName(name string) {

	o.Name = &name
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparsePCFWAccountMirrorTerraform) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparsePCFWAccountMirrorTerraform) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// DeepCopy returns a deep copy if the SparsePCFWAccountMirrorTerraform.
func (o *SparsePCFWAccountMirrorTerraform) DeepCopy() *SparsePCFWAccountMirrorTerraform {

	if o == nil {
		return nil
	}

	out := &SparsePCFWAccountMirrorTerraform{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparsePCFWAccountMirrorTerraform.
func (o *SparsePCFWAccountMirrorTerraform) DeepCopyInto(out *SparsePCFWAccountMirrorTerraform) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparsePCFWAccountMirrorTerraform: %s", err))
	}

	*out = *target.(*SparsePCFWAccountMirrorTerraform)
}

type mongoAttributesPCFWAccountMirrorTerraform struct {
	ID          bson.ObjectId `bson:"_id,omitempty"`
	Description string        `bson:"description"`
	Name        string        `bson:"name"`
	Namespace   string        `bson:"namespace"`
}
type mongoAttributesSparsePCFWAccountMirrorTerraform struct {
	ID          bson.ObjectId `bson:"_id,omitempty"`
	Description *string       `bson:"description,omitempty"`
	Name        *string       `bson:"name,omitempty"`
	Namespace   *string       `bson:"namespace,omitempty"`
}
