# Model
model:
  rest_name: awsendpoint
  resource_name: awsendpoints
  entity_name: AWSEndpoint
  package: ngfw
  group: core/ngfw
  description: |-
    Represents the NGFW endpoint where the NGFW attaches.
    This object is a sub-object of NGFWAttachment.
  detached: true

# Attributes
attributes:
  v1:
  - name: endpointID
    description: The AWS endpoint created by the NGFW.
    type: string
    exposed: true
    stored: true
    read_only: true

  - name: status
    description: The status of the of endpoint.
    type: enum
    exposed: true
    stored: true
    read_only: true
    allowed_choices:
    - Creating
    - Updating
    - Deleting
    - Accepted
    - Failed
    autogenerated: true
    default_value: Creating

  - name: statusReason
    description: The status description of endpoint.
    type: string
    exposed: true
    stored: true
    read_only: true

  - name: subnetID
    description: The AWS subnet ID.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: xxxxxxxxx
