# Model
model:
  rest_name: mirrorscalegroup
  resource_name: mirrorscalegroups
  entity_name: MirrorScaleGroup
  package: discovery
  group: core/discovery
  description: |-
    Includes name and availability zones of an auto-scaling group that may be
    eligible for traffic mirroring.
  extends:
  - '@named'
  detached: true

# Attributes
attributes:
  v1:
  - name: availabilityZones
    description: The availability zones associated with the auto-scaling group.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true

  - name: unmatchedAvailabilityZones
    description: |-
      The availability zones associated with the auto-scaling group that are not
      associated with the firewall.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true
