# Model
model:
  rest_name: firewallrule
  resource_name: firewallrules
  entity_name: FirewallRule
  package: ngfw
  group: core/ngfw
  description: Represents a firewall rule.
  get:
    description: Retrieves the firewall rule with the given ID.
  update:
    description: Updates the firewall rule with the given ID.
  delete:
    description: Deletes the firewall rule with the given ID.
  extends:
  - '@identifiable-stored'
  - '@namespaced'
  - '@base'
  - '@zoned'
  - '@timeable'

# Attributes
attributes:
  v1:
  - name: TLSDecryption
    description: TLS Decryption.
    type: enum
    exposed: true
    stored: true
    allowed_choices:
    - None
    - Outbound
    - Inbound
    default_value: None

  - name: TLSDecryptionCertificateID
    description: The Certificate ID used for TLS Decryption.
    type: string
    exposed: true
    stored: true

  - name: URLCategories
    description: URL Categories. Any if nil.
    type: ref
    exposed: true
    subtype: firewallurlcategorycriteria
    stored: true
    extensions:
      refMode: pointer

  - name: action
    description: The action the firewall should take.
    type: enum
    exposed: true
    stored: true
    allowed_choices:
    - Deny
    - Allow
    - ResetServer
    - ResetBoth
    default_value: Deny

  - name: applications
    description: Application matching criteria. Any if nil.
    type: ref
    exposed: true
    subtype: firewallapplicationcriteria
    stored: true
    extensions:
      refMode: pointer

  - name: destination
    description: Destination matching criteria. Any if nil.
    type: ref
    exposed: true
    subtype: firewalltargetcriteria
    stored: true
    extensions:
      refMode: pointer

  - name: logging
    description: Log this rule when hit.
    type: boolean
    exposed: true
    stored: true

  - name: parentID
    description: |-
      The FirewallTemplate ID, FirewallRuleset ID, or FirewallCommittedRuleset ID
      to which the rule belongs.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: parentType
    description: The type of parent ID to which the rule belongs.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: priority
    description: Values 1-100 for a Templates and 101+ for a Ruleset.
    type: integer
    exposed: true
    stored: true
    required: true
    example_value: 1
    min_value: 1

  - name: protoports
    description: Protocols and Ports. Any if nil.
    type: ref
    exposed: true
    subtype: firewallprotoportscriteria
    stored: true
    extensions:
      refMode: pointer

  - name: source
    description: Source matching criteria. Any if nil.
    type: ref
    exposed: true
    subtype: firewalltargetcriteria
    stored: true
    extensions:
      refMode: pointer
