# Model
model:
  rest_name: logincidentdetailsquery
  resource_name: logincidentdetailsqueries
  entity_name: LogIncidentDetailsQuery
  package: logging
  group: core/log
  description: Provide details on a Log Incident, including traffic and threat log
    information.

# Attributes
attributes:
  v1:
  - name: attackerIP
    description: The attacker IP address.
    type: string
    exposed: true
    required: true
    example_value: 212.44.7.91

  - name: firewallName
    description: The NGFW name.
    type: string
    exposed: true
    required: true
    example_value: firewall1

  - name: logResult
    description: The result of the query.
    type: refList
    exposed: true
    subtype: firewalllog
    read_only: true
    autogenerated: true
    extensions:
      refMode: pointer

  - name: victimIP
    description: The victim IP address.
    type: string
    exposed: true
    required: true
    example_value: 212.3.41.8
