# Model
model:
  rest_name: pcfwaccount
  resource_name: pcfwaccounts
  entity_name: PCFWAccount
  package: ngfw
  group: onboarding
  description: Represents Prisma Cloud Firewall Account.
  get:
    description: Retrieve the status of the account.
  update:
    description: retries updating the role ARNs with NGFW.
  delete:
    description: offboard the account.
  extends:
  - '@namespaced'
  - '@identifiable-stored'
  - '@timeable'
  - '@zoned'

# Attributes
attributes:
  v1:
  - name: AWSAccountID
    description: AWS Account ID.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: 640574671726

  - name: NGFWCFTHash
    description: NGFW cloud formation template hash.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: NGFWExternalID
    description: NGFW external ID.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: NGFWOnboardingStatus
    description: NGFW onboarding status.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: NGFWSNSTopicARN
    description: NGFW SNS Topic ARN.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: NGFWServiceAccountID
    description: NGFW AWS service account ID.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: NGFWTenantID
    description: NGFW tenant ID.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: decryptionRoleARN
    description: AWS rulestack decryption role ARN.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: arn:aws:iam::640574671726:role/DecryptionRole

  - name: endpointRoleARN
    description: AWS endpoint role ARN.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: arn:aws:iam::640574671726:role/CustomerManagedEndpoint

  - name: logDestination
    description: The log destination for logging.
    type: string
    exposed: true
    stored: true
    required: true
    example_value: s3://640574671726-us-east-1-api-auth-bucket/Logging

  - name: loggingRoleARN
    description: AWS logging role ARN.
    type: string
    exposed: true
    stored: true
    example_value: arn:aws:iam::640574671726:role/LogMetricRole

  - name: primaryAccount
    description: indicates the primary AWS account.
    type: boolean
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: status
    description: status of account.
    type: enum
    exposed: true
    stored: true
    read_only: true
    allowed_choices:
    - Creating
    - Pending
    - Success
    - Failed
    - Deleting
    autogenerated: true

  - name: statusReason
    description: status failure reason.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
